### ISSUE TITLE
UI information layout: move data type out of the way

### ISSUE THREAD

**Issue by proccaserra** [metadatacenter/cedar-template-editor#10]
Data Type (text,date) should not be so prominent in the UI: it (at least for me) hides the most important bit of information: what should be reported.
For some reasons, I find the current position of that information token distracting and confusing.

suggestion: move 'data type' information in line with the text box on the right hand side, before the 'x' delete button

**Comment by martinjoconnor** [comment]
Current UI considerably different so closing.
