### ISSUE TITLE
Paging of forms

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-template-editor#104]
The page functionality is broken. When filling out a template that has multiple pages, only the first page is shown.

**Comment by martinjoconnor** [comment]
Also look at #119.

**Comment by martinjoconnor** [comment]
Pages turned off for the moment. Need to fix.

**Comment by martinjoconnor** [comment]
Merged in metadatacenter/cedar-project#28

I want to be able to edit an existing page break, to add title or description. (Note re #119: not sure what difference between section and page breaks are conceptually (one's bigger, I know). They are much more useful if one can associate display text with them.

What about separate static title field?

**Comment by willrett** [comment]
we now support both paging and section breaks
