### ISSUE TITLE
Unknown field in the model

### ISSUE THREAD

**Issue by egyedia** [metadatacenter/cedar-template-editor#105]
We just checked the JSON that gets saved in our database, and we found this field there, inside _ui
 "is_cardinal_field": true
There are several problems with the field:
 * It isnot following our naming convention, which is camelcase for fields.
 * We should not have fields saved into the model that are not present in the model specification

If it is really needed, maybe it could be stored in the "_tmp" object.
If you consider that the field is important and the model should be changed, let us know, and lets talk about the details.

**Comment by marcosmartinezromero** [comment]
Could be related to #109
