### ISSUE TITLE
index-remote.html explanation

### ISSUE THREAD

**Issue by egyedia** [metadatacenter/cedar-template-editor#107]
Could somebody explain to us what is the purpose of 
index-remote.html

Thank you,

Attila

**Comment by dylanvaughn** [comment]
@egyedia it looks like it was added here:

https://github.com/metadatacenter/cedar-template-editor/commit/3ccd4c209399a308c7267412c8d04e485492e0ae

It seems very similar to index.html.  Maybe you created it when doing the merge because of conflicts?

Regardless I think it can be removed.

**Comment by egyedia** [comment]
Thank you,

I removed the file
