### ISSUE TITLE
JSON schema viewer nondeterministic (actually deterministic, but wrong) behaviour

### ISSUE THREAD

**Issue by egyedia** [metadatacenter/cedar-template-editor#109]
The bug described below could have other implications as well aside that it makes the JSON viewer show different things on the same page after some clicks. I did not investigate.

The JSON viewer should always show the whole template/element, independently of the context.

Steps to reproduce:
	* Go to "Role Selector" => "Design Template"
	* Create new element, called "Simple text element"
	* Add a text field, name it tf1, save element
	* Create new template, called "Simple text template"
	* Add the previously creasted "Simple text element" to it
	* Save the template
	* Go to "Role Selector" => "Edit Metadata"
	* Click "Fill out template"
	* Pick "Simple text template"
	* Click on the "Show Template JSON" icon (top one)
	* The JSON that is shown will start at
		"title": "Simple text element element schema",
	* Reload the page
	* The JSON that is shown will start at
		"title": "Simple text template template schema",

To reproduce it again after the template and the element were saved
	* Go to template elements, open the "Simple text element"
	* Go to populate templates, pick the "Simple text template"
	* Click on the "Show Template JSON" 
	* Reload the page

**Comment by martinjoconnor** [comment]
Related to #108.
