### ISSUE TITLE
Disable edit/delete icons in embedded elements

### ISSUE THREAD

**Issue by marcosmartinezromero** [metadatacenter/cedar-template-editor#116]
When adding a pre-canned element to a template, there are icons to edit the element and to edit/delete the embedded elements/fields, which should be disabled.  (Edit, delete icons of nested fields and elements.)

**Comment by willrett** [comment]
![screen shot 2016-03-21 at 11 28 02 am](https://cloud.githubusercontent.com/assets/4739879/13929590/14e24dc8-ef58-11e5-90b6-554462485512.png)
