### ISSUE TITLE
The number of levels of the ontology tree that can be shown in the UI are limited by the width of the section that contains the tree

### ISSUE THREAD

**Issue by marcosmartinezromero** [metadatacenter/cedar-template-editor#12]
![screen shot 2016-02-17 at 9 30 57 am](https://cloud.githubusercontent.com/assets/7634440/13118525/6811c83e-d559-11e5-877d-6d6d01693532.png)

**Comment by dylanvaughn** [comment]
@marcosmartinezromero is this resolved now?

**Comment by marcosmartinezromero** [comment]
Yes. I will close this issue. Thanks.
