### ISSUE TITLE
Implement: Authorization. Groups, and Folders

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#126]
Implementation phase for designs in #45.

**Comment by egyedia** [comment]
https://docs.google.com/document/d/1QIllUxFSSr0g7dm9R7r38Gu9nCUAlJgQjcHW_zuQU3o/

https://docs.google.com/document/d/1YXRIlriWcQwzbZn-AiW36XUTo414IuLama_RQtvPdAg/

https://docs.google.com/document/d/1_ni54EJ-xVdfCpssaEyUGJSfRFg0bOnI5LPbhLirbN4/

https://docs.google.com/document/d/1QeJ0TTq4R4nOzNMwV-OxmANF76FAiNuOpcxBw8OYyCA/

https://docs.google.com/document/d/1LFQYkfq6F0J3Xnjvfu2pa1oSVriffe5mwc_aoszeOyg/

https://docs.google.com/document/d/1gdJeSj8QmohWLnJSDvIcyeyq5qCkYIagCXOX200se5I/
