### ISSUE TITLE
Need Cancel button on instance editor

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#139]
Currently no way to cancel.

**Comment by graybeal** [comment]
and on template editor

**Comment by willrett** [comment]
we now have three buttons: save, cancel and clear.  the cancel button now removes changes since the last save.  when we get the new layout we will have a back arrow in the upper left to go out of edit or populate mode, so using cancel to go back to browse view will not be necessary.
