### ISSUE TITLE
Visual indication that help text is filled out

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#157]
When designing template/element/field it might be nice to visually see that help text has been filled out for a field in summary mode.

<img width="739" alt="screen shot 2016-04-04 at 3 48 44 pm" src="https://cloud.githubusercontent.com/assets/1731323/14266428/fd680efa-fa7c-11e5-8888-e09701e164b2.png">

Similar in nature to #23.

**Comment by graybeal** [comment]
Is this same as #370 ?

**Comment by martinjoconnor** [comment]
Yup. Closed #370.

**Comment by martinjoconnor** [comment]
Related to https://github.com/metadatacenter/cedar-project/issues/626

**Comment by willrett** [comment]
Same as #626
