### ISSUE TITLE
Ontology tree is not rendered correctly after collapsing it

### ISSUE THREAD

**Issue by marcosmartinezromero** [metadatacenter/cedar-template-editor#167]
After expanding and then collapsing again an ontology branch, the children are not hidden.

![screen shot 2016-04-05 at 4 02 08 pm](https://cloud.githubusercontent.com/assets/7634440/14301424/91c18d54-fb4c-11e5-88d8-ea13f858594b.png)

**Comment by martinjoconnor** [comment]
Thinking about replacing the tree widget with a pre-canned one.

**Comment by dylanvaughn** [comment]
We actually used a different tree widget for the search facets by the way.
