### ISSUE TITLE
Show better error when user enters invalid URL

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#168]
Currently system shows partially rendered screen and red error panel in bottom corner.

Instead show top level error, per Google:

https://docs.google.com/document/d/1_mFW0VvZysWwadp2F1qvDi2b_5MDtvqNWzjZ3_TFB/edit

**Comment by martinjoconnor** [comment]
Partially fixed. We should show user-level popups for certain errors (e.g, invalid folder id) instead of read warning boxes.

**Comment by graybeal** [comment]
Google doc link above is invalid.

**Comment by martinjoconnor** [comment]
This seems to be fixed. I get sensible errors when entering garbage URLs for several test cases. Are there cases that give poor error messages?
