### ISSUE TITLE
Spreadsheet UX suggestions

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-template-editor#174]
I think I may have mentioned these issues before, but trying to add data in CEDAR using the spreadsheet format, just would not work as it currently is working. 

1) Need more real estate in the browser window, so many more fields can be entered before scrolling.
2) Would need select, then drag and drop for the Cells. For instance if I was entering "Species" for 20 subjects, I would want to pick the "Species" from a drop down in the first row, then drag and drop that species for the next 19 rows, rather than have to pick from drop down in each row. This functionality existed in many of LIMS web based frameworks, we evaluated several years ago, when working for Gene Logic.
3) There are no drop downs in the spreadsheet format. They are there in the single page format.

**Comment by marcosmartinezromero** [comment]
Summary of possible additional features:
- Increase spreadsheet size (we could show it using a modal)
- Add/delete rows from the spreadsheet view
- Fix representation of nested elements and nested multiple-instance fields. The element/field name and icon should be shown.

**Comment by graybeal** [comment]
Also reference the need for handling ontology term selection, and other constraints that would apply to the regular fields (including validation on the fly).

**Comment by willrett** [comment]
1. added fullscreen so there is lots of real estate
2. drop downs for controlled terms are working
3. add and delete rows from spreadsheet view working with a context menu accessed by right click
4. spreadsheet mode is disabled for templates with multi-answer fields or elements with nested elements
5. pasting controlled terms works
