### ISSUE TITLE
Multiple instances for field with value constraints fails at runtime

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-template-editor#175]
The selected values are not stored into the Output JSON

![screen shot 2016-04-08 at 11 50 30 am](https://cloud.githubusercontent.com/assets/7634440/14394350/a6411bd8-fd80-11e5-9981-19bbc5b397bb.png)

**Comment by martinjoconnor** [comment]
Seems to put constraints into first instance only.

**Comment by martinjoconnor** [comment]
Merged into #491.
