### ISSUE TITLE
problem saving element

### ISSUE THREAD

**Issue by proccaserra** [metadatacenter/cedar-template-editor#178]
created a element called TEST-A1.
tried to add a field and save

![image](https://cloud.githubusercontent.com/assets/517736/14429889/367e6e26-fff7-11e5-8ca3-e4ef13941026.png)

OS El Capitan:
Browser: Chrome 49.0.2623.110

**Comment by martinjoconnor** [comment]
You need to click + on the field to save it first.

**Comment by proccaserra** [comment]
UX: not that intuitive. Can save button save everything that needs to be saved ?
Alternately, the UI needs to clearly identify where the problem is -> current error message is not helpful
