### ISSUE TITLE
Not possible to remove an element with 'Clear it'

### ISSUE THREAD

**Issue by proccaserra** [metadatacenter/cedar-template-editor#182]
Trying to remove test elements using  'Clear it' button and X button.
UI asks to confirm, removes all attribute and label from pain pane but element can still be found under 'Add an element' drop down list

**Comment by proccaserra** [comment]
I managed to deleted that element, going to the dashboard -> see all -> (finding element) and clicking (X) button.

i. add mouse over msg to the action button (currently only showing Name for the (X) button and Name + UIID for the edit button

ii. add a delete button in addition to 'clear' and 'save'.

**Comment by proccaserra** [comment]
Following up on this. went back to check the behavior of 'clear it'.
It drops an string in the 'Element Name' and 'Element Description' fields in the dark blue bar but retains the element on the page.
This the confusing bit. One does not how deep the cleaning is. Test-A3 box is still display, hitting the 'save' button shows no message, hitting 'clear it' does drop the box.

![image](https://cloud.githubusercontent.com/assets/517736/14433066/ab712ab8-0004-11e6-996f-e1226e6ac3e8.png)

**Comment by proccaserra** [comment]
More on this tickets: Now trying to start from scratch, going to Dashboard, then Selecting 'Instrument Template' from , then hitting the json viewer toggle button and getting very inconsistent JSON output.

once it contains segments related to 'TEST-A3' element (the one i was trying to clear), then got a session reset, now I am getting the right json for the template but still have a 'sticky' empty field.  Trying to edit it causes a cardinality attribute to show up but saving fails to close and hitting the (x) delete fields from the template (which it should not probably do)

![image](https://cloud.githubusercontent.com/assets/517736/14433879/0e6170bc-0008-11e6-8681-3f06c899ee3e.png)

**Comment by martinjoconnor** [comment]
Possibly related to #248.

**Comment by martinjoconnor** [comment]
Works now.
