### ISSUE TITLE
Element designer/add an element menu: allow filtering while typing

### ISSUE THREAD

**Issue by proccaserra** [metadatacenter/cedar-template-editor#183]
as number of elements grows, scrolling will become inconvenient.

**Comment by martinjoconnor** [comment]
One option is to collapse finished elements using the '-' icon on the top left of each element. We may look at auto-collapsing too.

**Comment by martinjoconnor** [comment]
Ah - misunderstood. Thought you were talking about the form creation.

We are in the process of replacing the element selection with faceted search functionality to address this problem.

**Comment by martinjoconnor** [comment]
New search addresses this.
