### ISSUE TITLE
Session reset for no obvious reason

### ISSUE THREAD

**Issue by proccaserra** [metadatacenter/cedar-template-editor#184]
So obvious to identify the trigger, but on several occasions, in spite of continuous activity with the tool, the session is reset, forcing me to log back in. Is there a fixed time session time-out?

**Comment by martinjoconnor** [comment]
There is - but it should be 24 hours (it was shorter). However, it is possible that the server you are using does not have this longer timeout. We will update the server later today.

Let us know if it happens again.

**Comment by martinjoconnor** [comment]
May have fixed with additional Keycloak timeout setting.
