### ISSUE TITLE
Save instance as draft

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#185]
Allow instance to be saves in draft form, without checking for required fields.

**Comment by martinjoconnor** [comment]
Related to auto-save issue #38.

**Comment by marcosmartinezromero** [comment]
It also applies to templates and elements

**Comment by graybeal** [comment]
Consider making this the default (switch the model around so work is always saved)

**Comment by graybeal** [comment]
Addressed by #38
