### ISSUE TITLE
Delete 'Add an Item' Area

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#19]
Git rid of "Add an item" area.

**Comment by willrett** [comment]
where is the "add an item" area?

**Comment by martinjoconnor** [comment]
This puppy:

<img width="1014" alt="screen shot 2016-04-03 at 5 19 30 pm" src="https://cloud.githubusercontent.com/assets/1731323/14235918/4dcd161e-f9c0-11e5-9f78-4d6cf5b93ea6.png">

Now labeled "Add an existing element ...".

Present in both the template creator and element creator.

**Comment by martinjoconnor** [comment]
Really think there should be a cancel button here and in element creator too. Which should prompt for exit if form is not empty.
