### ISSUE TITLE
Class not always centered in ontology tree view

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#190]
When displaying tree view of ontology in controlled term modal the searched-for class is not always centered. Seems to be a timing issue because repeated searches for the same class sometimes result in a properly-centered view and sometimes do not.

Good test class is Assay in OBI.

**Comment by graybeal** [comment]
In at least one case there were multiple terms with the same label. That may be the cause of this in other cases too.

**Comment by martinjoconnor** [comment]
@marcosmro Is this fixed by the latest code?
