### ISSUE TITLE
First visit to site doesn't succeed

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-template-editor#191]
I'm finding that the first time I access either system from safari or chrome from home, the progress bar seems to complete but the page is not updated. The second time (e.g., on reload), the auth screen appears normally.

**Comment by martinjoconnor** [comment]
Not sure if still true, and hard to reproduce. Will check on next software update.

**Comment by graybeal** [comment]
(Replying blind, offline from airplane.) There was at least one fix, for login weird messes, that may have fixed this. Can sign off pending further issue showing up, if you want.

Sent from my iPhone

On May 24, 2016, at 12:07 PM, martinjoconnor <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure if still true, and hard to reproduce. Will check on next software update.

**Comment by graybeal** [comment]
I think this was fixed by Marcos in #234
