### ISSUE TITLE
Confirm hook on back button when editing

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#20]
Currently browser back button can be used in place where it should be protected, potentially losing information. We should ask for confirmation when the user wants (or accidentally tries to) leave a page (element, template or instance) with unsaved data on it.   Need the warning "do you want to stay on this page?

**Comment by martinjoconnor** [comment]
U15, https://docs.google.com/spreadsheets/d/1RvP7hQO_Rw1-XT_Vj0hmKBSKdlPdPp8v0O-KySssM_M/edit#gid=0

**Comment by graybeal** [comment]
even when not editing but just viewing an editing modal, back button results in darkened background screen and no foreground screen (on Safari). No obvious way to correct -- have to reload page.
