### ISSUE TITLE
Add a way to show the provenance in the UI for fields, template elements and templates.

### ISSUE THREAD

**Issue by agbeltran** [metadatacenter/cedar-template-editor#202]
Related to the issue https://github.com/metadatacenter/cedar-template-server/issues/6
It would be great to visualise the provenance info in the UI too (with a toggle so that it can be hidden or shown).

**Comment by martinjoconnor** [comment]
Being addressed by https://github.com/metadatacenter/cedar-template-editor/issues/719 and https://github.com/metadatacenter/cedar-template-editor/issues/720
