### ISSUE TITLE
Make pre-generated  'Untitled' text selected

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#204]
In many places in CEDAR we set fields to a default of 'Untitled'. We should do this and make the entire text selected to that it can quickly be deleted. At present we have to individually delete its characters or do a select all and delete it then,

**Comment by graybeal** [comment]
#254 looks like duplicate

**Comment by martinjoconnor** [comment]
Yup - is duplicate.
