### ISSUE TITLE
Dropdown list of values for fields constrained using ontology terms is not scrollable

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-template-editor#210]
The dropdown with the list of possible values for a field that has been constrained using ontology terms is limited to a small number of values (approx. 15). The user may think that there are no more accepted values than those. When the user starts typing, new values are shown. Possible solution: implement"infinite scrolling" for the dropdown

**Comment by marcosmro** [comment]
Main cause of this issue was that we were using the BioPortal search endpoint to retrieve all classes in the ontology when the input search was empty (we were searching for '*'). However, the search endpoint returns a limited number of results, not all of them. We have implemented in the terminology server an endpoint to retrieve all classes from a given ontology. This endpoint is used when the user's query is empty instead of calling the search endpoint. Currently the dropdown list is populated with the top 500 results. This is a temporal fix, infinite scrolling would be the ideal solution.

**Comment by marcosmro** [comment]
Take a look at it to see if we need help from the BioPortal team

**Comment by willrett** [comment]
This doesn't need to be fixed. The user will type in more characters to refine the search and the list will be narrowed to a smaller set as they type.  That is the way autocomplete always works and the user expects there to be more.
