### ISSUE TITLE
can't create multiple entries of text metadata

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-template-editor#211]
Tried making a text field Multiple from 0..n. 

In the metadata editor, doing anything to leave a field (tab, +, click outside) results in the entered text being discarded.

**Comment by graybeal** [comment]
Can test it using field CL_Disease in https://cedar.metadatacenter.net/instances/create/https://repo.metadatacenter.net/templates/c8de796a-a4f9-4846-b66e-4634f64fb7bb?folderId=https:%2F%2Frepo.metadatacenter.net%2Ffolders%2F48752fe4-6e78-4608-aa77-2cd580c45065,

**Comment by graybeal** [comment]
Doesn't matter whether the field is just text or selected from ontology. One of our test cases for multiple choice should be when the selection is from an ontology -- not convinced the individual value fields look right, and I'm guessing the spreadsheet view might not work with ontologies. Not sure if we have a list of test cases, actually.

**Comment by graybeal** [comment]
Duplicates #213, deleting.

**Comment by kjcollins** [comment]
<img width="980" alt="screen shot 2016-07-06 at 2 42 32 pm" src="https://cloud.githubusercontent.com/assets/19827553/16635698/590a1fec-4388-11e6-98e6-9d73b591061f.png">


After populating the fields Public ID through Version in tab 1, clicking away from them, and returning to tab 1, fields are empty. 

However, the fields in Classifications List Item outside the imported item (item name, item type) save correctly and retain the information after clicking away and returning.
