### ISSUE TITLE
In class selection widget, model for handling class clicks in tree isn't right

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-template-editor#215]
I'm in the class selection tree. Even before the tree is populated, there is a term at the bottom with "Add" button. 
(1) It isn't obvious this is the same term that was selected in the previous display (and the widget), because those were bold caps and this is camel case regular font.

Now I click on something else. A new class appears below the original class, so now there are two classes that can be added. (Of course only one of them can be added, because as soon as I click Add this widget will close.)

![screen shot 2016-05-11 at 4 06 17 pm](https://cloud.githubusercontent.com/assets/1266896/15199436/f2020bf0-1792-11e6-9c4b-48bcaca95482.png)

Now I click on yet another thing. This new thing appears not as a third item, but replacing the second item. 
(2) So why did the second item not replace the first then? Not consistent, and not clear why it's not consistent.

**Comment by martinjoconnor** [comment]
@marcosmro This should be addressed by latest code I think?
