### ISSUE TITLE
Browsing ontologies should see number of terms

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-template-editor#217]
When browsing ontologies should see number of terms in each, and column should be labeled "Number of Terms" or "# of Concepts", not NO CLASSES (not sure where I saw that now, I can't find it).

![screen shot 2016-05-11 at 4 26 13 pm](https://cloud.githubusercontent.com/assets/1266896/15199707/80db591a-1795-11e6-9b20-b032e121ac30.png)

**Comment by proccaserra** [comment]
on the usability of this widget, the current color schema does not make it obvious the section is scrollable. the scroll bar is faint and does not pop-out -> add visual cues or a button 'more results' after the 5 first rows of results

**Comment by martinjoconnor** [comment]
Will be addressed by: https://github.com/metadatacenter/cedar-template-editor/issues/549
