### ISSUE TITLE
Static fields should not be added to template instances

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-template-editor#222]
Currently, if a template has some static fields (e.g. video, static text), all instances of the template will contain those static fields too, with an empty _value field inside. Example:

"video": {
    "_value": ""
  }

The purpose of static fields is just to provide some static content to guide users when filling out the template. Those fields cannot be filled out, they cannot contain metadata values. As a consequence, those fields should not be added to template instances.

**Comment by martinjoconnor** [comment]
Merged into #491.
