### ISSUE TITLE
Edit vs populate workflow confusion

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-template-editor#223]
When editing  a template, it's difficult to go between  editing the field and previewing it, i.e. in edit mode or not.  Ideally we would not have such a dramatic difference in layout between the two states and everything would like preview mode while still being editable..  Qualtrics and GoogleForms both do this nicely.

U7, https://docs.google.com/spreadsheets/d/1RvP7hQO_Rw1-XT_Vj0hmKBSKdlPdPp8v0O-KySssM_M/edit#gid=0

**Comment by martinjoconnor** [comment]
Ultimately, make edit and preview mode look identical?

**Comment by graybeal** [comment]
moved to backlog until we know exactly what issues we want to address, and how we want to address them.

**Comment by martinjoconnor** [comment]
Merged #459 into this: preview link

**Comment by martinjoconnor** [comment]
Merging this into #230.
