### ISSUE TITLE
Tabs under ontology tree are confusing

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#229]
U3, https://docs.google.com/spreadsheets/d/1RvP7hQO_Rw1-XT_Vj0hmKBSKdlPdPp8v0O-KySssM_M/edit#gid=0

**Comment by martinjoconnor** [comment]
Perhaps open first one by default?

**Comment by graybeal** [comment]
Just put small spaces between the tab segments and be done with it
