### ISSUE TITLE
Help text for card icons are not useful

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#231]
U6, https://docs.google.com/spreadsheets/d/1RvP7hQO_Rw1-XT_Vj0hmKBSKdlPdPp8v0O-KySssM_M/edit#gid=0

**Comment by martinjoconnor** [comment]
Move some items into a menu?

**Comment by willrett** [comment]
got rid of card icons.  all actions on nav have a tooltip
