### ISSUE TITLE
Allow instance save with invalid values without data loss

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#232]
U8, https://docs.google.com/spreadsheets/d/1RvP7hQO_Rw1-XT_Vj0hmKBSKdlPdPp8v0O-KySssM_M/edit#gid=0

Throws out invalid values!

**Comment by graybeal** [comment]
Does this task mean 'make it possible'?

**Comment by martinjoconnor** [comment]
No - I have changed title. When save-as-draft (#185) is supported then it will make sense - but that will require 'draft' mode.

**Comment by graybeal** [comment]
why isn't everything draft mode in the first place? that's the more human behavior by far

**Comment by graybeal** [comment]
Any entries that have been made should remain unless the person acknowledges they will be lost (in response to a prompt). It's OK for bad or empty values to be in a saved instance.

**Comment by willrett** [comment]
save with bad values
