### ISSUE TITLE
Search vs. browse confusion on controlled term dialog

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#235]
U12, https://docs.google.com/spreadsheets/d/1RvP7hQO_Rw1-XT_Vj0hmKBSKdlPdPp8v0O-KySssM_M/edit#gid=0

**Comment by marcosmartinezromero** [comment]
Discard the Browse field and use only a Search field with three checkboxes: Ontology classes, Ontologies and Value sets.
