### ISSUE TITLE
Can't create element in template editor

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#239]
U18, https://docs.google.com/spreadsheets/d/1RvP7hQO_Rw1-XT_Vj0hmKBSKdlPdPp8v0O-KySssM_M/edit#gid=0

**Comment by marcosmartinezromero** [comment]
When you update the element from the template, is the independent element updated too, is a new element created? This issue is related to versioning and solving it is not trivial

**Comment by martinjoconnor** [comment]
Merged into #230
