### ISSUE TITLE
Improve Template/Element Name and Description Fields

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#24]
Currently, these fields look like they are filled out. The user does not know that he/she has to provide values for them. Also, the template/element icon on the left of the template/element name field is confusing. The user may think that there is some action associated to it, but nothing happens when clicking on it.

**Comment by willrett** [comment]
These are now defaulted to Untitled.  I would move them out of the header and  into the set of questions.
