### ISSUE TITLE
Create + symbol confusing

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#240]
U19, https://docs.google.com/spreadsheets/d/1RvP7hQO_Rw1-XT_Vj0hmKBSKdlPdPp8v0O-KySssM_M/edit#gid=0

**Comment by martinjoconnor** [comment]
Tooltip. Look at Google Inbox.

**Comment by willrett** [comment]
the plus should turn into the form icon on hover.

**Comment by willrett** [comment]
i addd tooltips
