### ISSUE TITLE
All card resource icons look alike

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#241]
U20, https://docs.google.com/spreadsheets/d/1RvP7hQO_Rw1-XT_Vj0hmKBSKdlPdPp8v0O-KySssM_M/edit#gid=0

**Comment by martinjoconnor** [comment]
Try some approaches to visually distinguish them.

**Comment by willrett** [comment]
We can show folders first as Drive does.  Make them smaller because they have no description
