### ISSUE TITLE
Forgot password is not working

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#242]
U21, https://docs.google.com/spreadsheets/d/1RvP7hQO_Rw1-XT_Vj0hmKBSKdlPdPp8v0O-KySssM_M/edit#gid=0

**Comment by egyedia** [comment]
I set it up on cedar.metadatacenter.net with:

smtp server: smtp-unencrypted.stanford.edu
port: 25
from email: cedar@metadatacenter.net

If we want to use smtp.stanford.edu with SSL, we will need to import the certificate into the accerts. This means stopping and starting the server, so let's not do this during business hours.
