### ISSUE TITLE
Limited date format support

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#243]
U23, https://docs.google.com/spreadsheets/d/1RvP7hQO_Rw1-XT_Vj0hmKBSKdlPdPp8v0O-KySssM_M/edit#gid=0

**Comment by graybeal** [comment]
related to #289 ?

**Comment by martinjoconnor** [comment]
Yup - 289 supersedes. Have copied usability link to it.
