### ISSUE TITLE
Show term definition string in controlled term dialog

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#249]
U28, https://docs.google.com/spreadsheets/d/1RvP7hQO_Rw1-XT_Vj0hmKBSKdlPdPp8v0O-KySssM_M/edit#gid=0

**Comment by graybeal** [comment]
Now fixed for search, should also be fixed in this modal:

![screen shot 2016-06-20 at 12 12 21 pm](https://cloud.githubusercontent.com/assets/1266896/16207121/64a93766-36e0-11e6-9007-b0ab39f1bac9.png)
