### ISSUE TITLE
Add Value Type incorrectly available on some fields

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#25]
At present, the tool makes it possible to associate “Value Types” to any field type. However, this does not make sense for some field types (e.g., paragraph).

**Comment by willrett** [comment]
which fields should have value types?

**Comment by martinjoconnor** [comment]
I guess it is easier to recognize which fields should not. Paragraph, phone number, numeric, and date currently have this possibility and should not. The others look correct.
