### ISSUE TITLE
Customize login screen

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#252]
Also see U33, https://docs.google.com/spreadsheets/d/1RvP7hQO_Rw1-XT_Vj0hmKBSKdlPdPp8v0O-KySssM_M/edit#gid=0

**Comment by martinjoconnor** [comment]
Need something that reflects CEDAR design for 0.8. Perhaps get static web site company on it?

**Comment by graybeal** [comment]
Yup, will assign to wired moon

**Comment by egyedia** [comment]
We should send them the HTML for the factory preset Login screen of Keycloak, they should include all those inputs and links which are there.
Also, we should ask them to register and look around in the tool, to get a sense of the current color scheme.

**Comment by graybeal** [comment]
I gave them the URLs for cedar and staging, so they can pull the HTML themselves if they want. They asked if they could do this as a mockup, in order to save us the cost of them learning key cloak.

**Comment by graybeal** [comment]
Asked them to register for that purpose, but also to look around. See #

**Comment by martinjoconnor** [comment]
Artwork received from Wiredmoon. Need to integrate HTML/CSS into Keycloak.

**Comment by graybeal** [comment]
Second round of artwork available on Box about 7 layers down. See folder at https://stanfordmedicine.box.com/s/jw2qwv2wunz20iewcoii6s111qft3sx4 
(Technical Resources > Website > Graphics > WiredMoon  Artwork > CEDAR Login)

There are 2 versions, one with watermark in back and one without. And then there's the EPS watermark. I prefer a watermark but somewhat bigger than how they did it -- but given time constraints, maybe we just use the one without?

**Comment by graybeal** [comment]
my latest proposed login screen text:
```
This is a beta release of the CEDAR Workbench, designed to make better metadata with less work. This initial release addresses simple metadata collection and setup—the service will add many more capabilities in coming months. For more information, visit our <a href="https://metadatacenter.org/tools-training/orientation">CEDAR Orientation page</a>.
```

**Comment by martinjoconnor** [comment]
Think we are selling ourselves very short with the 'simple metadata collection'. Would argue that current system allows very rich metadata specification and collection. What it is weak is workflow and metadata management  functionality - exciting features that are  coming soon!

**Comment by graybeal** [comment]
OK, then:
```
This is a beta release of the CEDAR Workbench, designed to make better metadata with less work.
This initial release addresses rich metadata setup and collection—stay tuned for more, 
we will extend these capabilities in coming months! For more information, check out our 
<a href="https://metadatacenter.org/tools-training/orientation">CEDAR Orientation</a>.
```

**Comment by graybeal** [comment]
OK then:
```
This is a beta release of the CEDAR Workbench, designed to make better metadata easier.
This initial release addresses rich metadata setup and collection—and stay tuned for more, 
we're extending these capabilities in coming months! For more information, check out our 
<a href="http://metadatacenter.org/tools-training/orientation">CEDAR Orientation</a>.

**Comment by egyedia** [comment]
The login screen is working on my machine, but we definitely need the two images as transparent PNG files
