### ISSUE TITLE
Default 'Untitled' text should be selected

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#254]
U36, https://docs.google.com/spreadsheets/d/1RvP7hQO_Rw1-XT_Vj0hmKBSKdlPdPp8v0O-KySssM_M/edit#gid=0

**Comment by graybeal** [comment]
Or at least, it should disappear -- it doesn't have to actually be text in the field, it could just be a hint instead.

**Comment by willrett** [comment]
select all of text input when field or element selected makes it easier to edit.

**Comment by martinjoconnor** [comment]
Reopening because it does not yet work for template and element names.
