### ISSUE TITLE
Keycloak timeout issues

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#265]
U1, https://docs.google.com/spreadsheets/d/1RvP7hQO_Rw1-XT_Vj0hmKBSKdlPdPp8v0O-KySssM_M/edit#gid=2002516404

**Comment by martinjoconnor** [comment]
This may be fixed. We need to monitor.

**Comment by martinjoconnor** [comment]
Still there. Has odd failure mode. It seems that when it fails it only fails on a resource save but prior to the save the user could still access the system.

**Comment by graybeal** [comment]
At a minimum need to make the situation recoverable, rather than losing work. (Saving on every field change would reduce this risk considerably.)

**Comment by martinjoconnor** [comment]
Have not seen in months. Closing.
