### ISSUE TITLE
Automatically collapse 'Add new resource' dialog

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#273]
If the user changes his/her mind and goes away from the dialog, it won't be closed. He/she needs to explicitly close it

U11, https://docs.google.com/spreadsheets/d/1RvP7hQO_Rw1-XT_Vj0hmKBSKdlPdPp8v0O-KySssM_M/edit#gid=2002516404

**Comment by marcosmartinezromero** [comment]
Solution: Auto-close it when the user leaves the dialog area or when the user clicks somewhere else

**Comment by willrett** [comment]
No longer applies.
