### ISSUE TITLE
Turn off auto-complete in text fields

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#275]
We should turn off the browser's autocomplete for text fields because it is irrelevant when entering answers

U33, https://docs.google.com/spreadsheets/d/1RvP7hQO_Rw1-XT_Vj0hmKBSKdlPdPp8v0O-KySssM_M/edit#gid=0

**Comment by graybeal** [comment]
Not always irrelevant, if people are entering information which is duplicate across multiple instances.

**Comment by martinjoconnor** [comment]
Yes - I sometimes find it useful too. (Just repeating text from spreadsheet above.)

**Comment by martinjoconnor** [comment]
Old and moot and nobody has complained for over a year.
