### ISSUE TITLE
Fix date/time fields (Separate Date, Time, DateTime fields?)

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#289]
Currently all these types are merged into one, which is confusing. 

Extracted from #58.

**Comment by martinjoconnor** [comment]
See also U23, https://docs.google.com/spreadsheets/d/1RvP7hQO_Rw1-XT_Vj0hmKBSKdlPdPp8v0O-KySssM_M/edit#gid=0

**Comment by proccaserra** [comment]
Date Field: 

data entry leads to storing incorrect values. Typing 23/12/1924 (or pasting 14/07/1974 from Excel cell) stores "10/06/2016 12:00 AM"

i. provide visual cues as to which format to use (and validation as one types)
or
ii. bring up calendar upon field activation to reduce clicking and ensure correct entries

OS: el capitan
Chrome Version 53.0.2785.116

**Comment by graybeal** [comment]
If all these types were merged into one, we would have all the features. Unfortunately, we only have one feature, the date feature, and it is buggy (see previous comment).  We don't have a time feature, and we don't have a date-time feature. Date-time is a very common timestamp form for logging events, we need these two features added.

**Comment by graybeal** [comment]
Note also Michelle's comments from April 13 below. Most of this is just about whether/how we validate, not relevant to this thread; but the relevant concern is that some people might like to enter partial dates in a data field. This can be done in a legal ISO8601 representation, and ideally we could allow for that possibility.

```
Question about a Date field: It's nice for the user that with a Date field, they are not required to put in an exact date, because often an exact date isn't known, or isn't appropriate (for ex: for a copyright date in the library world, we'll only be entering a year.) But in the output from CEDAR for this kind of field, the value the user puts in is data-typed XMLSchema#dateTime. Is this "legal" if the user doesn't actually put in a date in the proper format? Here's an example of CEDAR output that might not make sense:

 "copyrightDate": {
    "@value": "this is not a date",
    "@type": "xsd:dateTime"
  }

Same question for the "Link" field type. Example of output that might be invalid:

"subject": [
    {
      "@id": "this is not a URL"
    }

Maybe this is the same issue as Martin's #4 below about validating a URI.
```

**Comment by graybeal** [comment]
Reference #745
