### ISSUE TITLE
Help text in more places

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#29]
Add help icons and descriptions to the template editor in a lot more places. Increase font of current runtime help text. (Controlled term icon, Delete element, Done editing element, ...)

**Comment by willrett** [comment]
![screen shot 2016-03-22 at 7 30 49 am](https://cloud.githubusercontent.com/assets/4739879/13958634/159e5886-f00e-11e5-813b-cc3602d0f1be.png)

**Comment by martinjoconnor** [comment]
Has been addressed by recent updates,
