### ISSUE TITLE
Allow single click to open a folder?

### ISSUE THREAD

**Issue by agbeltran** [metadatacenter/cedar-template-editor#297]
It seems that to open a folder it is necessary to double-click it. I think a single click would do the trick and be more intuitive?

Thanks
<img width="1154" alt="screen shot 2016-06-03 at 16 23 35" src="https://cloud.githubusercontent.com/assets/1417033/15783868/cdd7024a-29a7-11e6-83f8-35b14d777040.png">

**Comment by martinjoconnor** [comment]
Have decided to stick with double for the moment to be consistent with behaviour of other resources.
