### ISSUE TITLE
Deleting a nested element

### ISSUE THREAD

**Issue by amrapalijz** [metadatacenter/cedar-template-editor#300]
Unable to delete a nested element.

**Comment by martinjoconnor** [comment]
Can you give more information so that we can reproduce this bug.

e.g., #299

**Comment by amrapalijz** [comment]
On https://cedar.metadatacenter.net
I created the element "Service Metadata", which consists of two nested elements: (i) Service Parameter Metadata and (ii) Service Response Metadata along with some fields outside of these two elements.
I cannot delete either of the two nested elements.
When I click on the cross sign on the right-hand side, nothing happens.
And another issue is that I cannot even collapse any of the elements in there.
![screen shot 2016-06-07 at 4 29 45 pm](https://cloud.githubusercontent.com/assets/713103/15878094/18b4608c-2ccd-11e6-80c0-a0342661e2e3.png)

**Comment by martinjoconnor** [comment]
Thanks for the report. 

Can you use cedar.staging.metadatacenter.net and verify that it is broken there. Staging has our latest code (it is usually updated very few days).
