### ISSUE TITLE
Feature request: Duplicating elements

### ISSUE THREAD

**Issue by amrapalijz** [metadatacenter/cedar-template-editor#301]
Feature request: there should be a way to duplicate an element with a click.
OR
Another way of duplicating an element or even a template could be by just copying the JSON description from one element and creating a new element and then just pasting that JSON. This feature is available in google refine to performing the operations done on one file on to another file: https://github.com/OpenRefine/OpenRefine/wiki/History. 

 
(I am unable to add labels to my git issues).

**Comment by martinjoconnor** [comment]
Merged into metadatacenter/cedar-project#33.
