### ISSUE TITLE
Bug - duplicate properties

### ISSUE THREAD

**Issue by amrapalijz** [metadatacenter/cedar-template-editor#302]
In https://cedar.metadatacenter.net, I created a template named "smartAPI". I looked at the JSON and found two instances of the two properties: (i) contactEmail and (ii) telephoneNumber as below:

"contactEmail": {
              "enum": [
                "https://schema.metadatacenter.net/properties/contactEmail"
              ]
            },
            "telephoneNumber": {
              "enum": [
                "https://schema.metadatacenter.net/properties/telephoneNumber"
              ]

"contactEmail1": {
          "enum": [
            "https://schema.metadatacenter.net/properties/7f0bee09-a6de-4611-9ea4-f7b1917e6ffb"
          ]
        },
        "telephoneNumber1": {
          "enum": [
            "https://schema.metadatacenter.net/properties/f5552bae-23dc-4c17-a876-50e664f52400"
          ]

I spoke to Debra and she said this is a bug because apparently I created these two fields and deleted them so they have two instances, which shouldn't be the case.

**Comment by martinjoconnor** [comment]
Merged into metadatacenter/cedar-project#21
