### ISSUE TITLE
Browser's attempt to pre-populate address fields does strange things

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-template-editor#306]
I created a contact element and added it to a template.  It has name and address fields.  When entering this my browser tries to pre-populate the fields, but instead enters United States into some other Cell Type field with restricted values.  Not sure why.

**Comment by martinjoconnor** [comment]
Do we have an element that show this behaviour?

**Comment by willrett** [comment]
This does not happen on the new form.
