### ISSUE TITLE
Do we need separate field type for controlled terms?

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#307]
At present we use a text field and then (optionally) restrict the value to come from an ontology. It does not seem natural that a 'text' field's value is a controlled term.

**Comment by graybeal** [comment]
if you want to clearly distinguish, call the non-controlled field 'free text' and the controlled term 'value selection'. A consideration is that we wanted to also allow the possibility for the pre-selected ontology choices to be suggested, but free text (which could also be a unique identifier) to be allowed also. 

I think it is odd, but we don't have to decide for 0.8 -- there is a migration path from the current model to a new model, as we add more subtle features.

(In fact the model is a bit richer still, in that we'd like to encourage the selection of a controlled term even to fill out free-text fields. We haven't pursued that yet, and don't need to for 1.0. Just be aware there is more complexity than just those two choices.)

**Comment by martinjoconnor** [comment]
Will be addressed by #286 in context of LD4P work.
