### ISSUE TITLE
The BioPortal 'tree' endpoint does not return the expanded tree

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-template-editor#317]
Sometimes, the BioPortal 'tree' endpoint (GET /ontologies/:ontology/classes/:cls/tree) does not provide the tree expanded to the given ontology class. A collapsed tree is returned

Example: invoke the tree endpoint for the term 'dendritic cell' in Cell Ontology (CL):
http://data.bioontology.org/ontologies/CL/classes/http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FCL_0000451/tree

**Comment by martinjoconnor** [comment]
@marcosmartinezromero: Is this still the case or did your recent fix address this?

**Comment by marcosmartinezromero** [comment]
Yes, it is still the case. It is something that needs to be fixed on the BioPortal side

**Comment by marcosmro** [comment]
Misha has fixed this issue. It will be deployed to BioPortal in 1-2 days.

**Comment by martinjoconnor** [comment]
Great - this looked bad when it happened (which was surprisingly frequently). We can close on next BioPortal release.
