### ISSUE TITLE
Create support page on CEDAR main web site

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-template-editor#334]
Create a support page, pointed to by help button and/or hamburger menu item, that guides users on how to get help and submit bugs.

Users can be sent to user-support@metadatacenter.org for bug reporting (see task #334), don't have to make a form.  We'll turn those into git issues as needed.

FAQs and other pages will be on GitHub, see task #335.

**Comment by martinjoconnor** [comment]
Have decided to put on Drupal.

**Comment by graybeal** [comment]
This is done, and help button points to it. http://metadatacenter.org/tools-training/support
