### ISSUE TITLE
Add wiki to Drupal for support info

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-template-editor#336]
Add wiki to GitHub using https://pages.github.com and Jekyll to generate nice wiki pages from markdown github pages. Include a FAQ.

**Comment by martinjoconnor** [comment]
@graybeal  Is this needed for 0.8 - or can it wait until 1.0?

**Comment by graybeal** [comment]
It isn't directly essential for 0.8, but we will need a way and a place to manage the technical support information we want to share with users. This was the 'cheapest' way I could think of.


FWIW, I was assuming I would contribute at least some to its creation, maybe a lot.

________________________________

**Comment by graybeal** [comment]
New plan is to do this on Drupal, not Github. First page is now created, at https://metadatacenter.org/tools-training/orientation

**Comment by martinjoconnor** [comment]
That link gives a "site can't be reached' error for me. Main site is fine.

**Comment by graybeal** [comment]
As soon as we verify the link works, this is ready to sign off. Can't verify right now because the http/https challenge I encouraged Alex to take on is ongoing....

**Comment by graybeal** [comment]
Tested and works now , closing.
