### ISSUE TITLE
+ icon erroneously appears in search mode

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#339]
Should be hidden in this mode

**Comment by martinjoconnor** [comment]
<img width="738" alt="screen shot 2016-07-25 at 8 11 34 pm" src="https://cloud.githubusercontent.com/assets/1731323/17124961/11a20432-52a4-11e6-91e6-e2300c55d1e1.png">

**Comment by willrett** [comment]
I think the  new button should  be visible at all times, even when searching.

**Comment by martinjoconnor** [comment]
Since user's current folder is being tracked I agree.
