### ISSUE TITLE
Property naming

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#34]
Allow users to provide user-friendly role names for nested fields and elements. Provide default names using the field or element names but allow override. Extend UI portion of model to store these names and use JSON-compatible unique field names in core JSON model. Allow types to be assigned to the roles. 

Roles are also required for template fields. For instance, some user could add a “Name” field to a template and call it “CL_Name”, and then add it to another template and call it “AR_name”. 
#295 builds on this to allow type assignment to roles.

**Comment by graybeal** [comment]
Description please?

**Comment by willrett** [comment]
part 1: saving propertyLabels for elements. done and checked in.  
part 2: keeping order and properties in sync with propertyLabels.  in progress

**Comment by willrett** [comment]
using debouncing to refresh edits for property names, 5 second delay before accepting edits.
