### ISSUE TITLE
Visual indication that collapsed facet is modified

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#350]
When a facet has been modified from its default state and then collapsed there is no visual indication of same, which can lead to confusion.

For example, if all templates, elements and instances are disabled in the type facets are those facets are collapsed the view is unchanged.

![screen shot 2016-06-24 at 1 22 58 pm](https://cloud.githubusercontent.com/assets/1731323/16349835/e152a086-3a0f-11e6-9844-bc07368dcc8b.png)

**Comment by willrett** [comment]
Maybe Type  should not be collapsable and filtering by type much more visible.   It is easy to forget that you are filtering one or more types.  I have found that I can't find something and later discover that I am filtering out that type.

**Comment by willrett** [comment]
Fixed by hiding RESET ALL unless filters have been modified.
