### ISSUE TITLE
Deleted resources sometimes remain on workspace

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#351]
When a resource is deleted in the workspace view it sometimes still appears on the workspace view (even though it has been successfully deleted from the server). If clicked on will give a server error.

Not consistently able to reproduce.

**Comment by martinjoconnor** [comment]
Can now reproduce. Seems to work if the last resource in a list is deleted. But deleting non-last resources leaves them on desktop. A manual refresh removes the deleted resource.

To reproduce:

. Go to a folder with a collection of resources, e.g., https://cedar.metadatacenter.net/dashboard?folderId=https:%2F%2Frepo.metadatacenter.net%2Ffolders%2F058864ed-a9c9-4c28-9401-3a1910352f13

. Add an element

. Change the sort order so it is no longer last

. Delete it

. Element will  still appear desktop

**Comment by willrett** [comment]
can't reproduce this
