### ISSUE TITLE
Blank multi-instance cardinality defaults very confusing

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#352]
Can we default to 1 to N or 0 to N? These are by far the most common situations. I have yet to find a max default of a specific number.

<img width="365" alt="screen shot 2016-06-25 at 10 10 43 am" src="https://cloud.githubusercontent.com/assets/1731323/16358070/5b83f848-3abd-11e6-8d69-6df1d0f778f4.png">

**Comment by martinjoconnor** [comment]
1 to N seems to be the case in ~90% of the multi-instance fields/elements I have created.

**Comment by willrett** [comment]
Are you saying limit the choices to 'single value',  '0..N',  and  '1..N'?

**Comment by martinjoconnor** [comment]
No - I mean put 1 as the default for the minimum value and N as the default for the maximum value.
