### ISSUE TITLE
Can't remove multi-instance behavior once selected

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#353]
Setting both max and min cardinality to 1 does not reset a multi-instance element or field to be single instance.

<img width="1000" alt="screen shot 2016-06-25 at 10 24 41 am" src="https://cloud.githubusercontent.com/assets/1731323/16358125/4212849a-3abf-11e6-9389-336e0614748d.png">

**Comment by willrett** [comment]
you have to empty out the field by selecting the "empty" option
