### ISSUE TITLE
Incorrect model encoding of multiple choice fields

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#371]
The options specified for a pick from a list field are stored in an ```options``` field in the ```_ui``` field. These should be stored in the ```_valueConstraints``` field because they are part of the specification - they are not just rendering choices. 

We will need a new field in the  ```_valueConstraint``` field to specify these options. The ```selectionType``` option should also be in the ```_valueConstraints``` field.

<img width="572" alt="screen shot 2016-07-13 at 1 18 09 pm" src="https://cloud.githubusercontent.com/assets/1731323/16818465/cd9bada2-48fc-11e6-9b85-04bafb134c5b.png">

**Comment by martinjoconnor** [comment]
Ditto for checkbox and radio fields. Also not the ```defaultOption``` field should be in the ```_valueConstraint``` field.

<img width="559" alt="screen shot 2016-07-13 at 1 28 27 pm" src="https://cloud.githubusercontent.com/assets/1731323/16818733/1fb5842c-48fe-11e6-8bc3-afc979b0a3b4.png">
 
<img width="541" alt="screen shot 2016-07-13 at 1 29 23 pm" src="https://cloud.githubusercontent.com/assets/1731323/16818738/23aaeba8-48fe-11e6-9b44-3ed10ad1cbf5.png">

**Comment by willrett** [comment]
_valueContstraints.literals should hold options, defaultOption, and selectionType

**Comment by martinjoconnor** [comment]
Merged into #491.
