### ISSUE TITLE
Template Creator Fields Checkbox Field

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#418]
Write E2E tests in category 'Checkbox Field' in [Template Creator Fields sheet](https://docs.google.com/spreadsheets/d/1JNLSp8gjc_owIzAR8Ww6HrGzkm7gHVORgHThTjChK8A/edit#gid=1817215732).

When done, update test row completion status in spreadsheet.

Also update totals sheet at [Totals Sheet](https://docs.google.com/spreadsheets/d/1JNLSp8gjc_owIzAR8Ww6HrGzkm7gHVORgHThTjChK8A/edit#gid=547615264).

**Comment by willrett** [comment]
https://docs.google.com/spreadsheets/d/12xWl2qGYJGHsEgnXR6Ur2w9lC2ya5-oEhX59DwrmP3k/edit?usp=sharing
