### ISSUE TITLE
Edit nested elements

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-template-editor#458]
make the edit form look like the metadata editor form

**Comment by martinjoconnor** [comment]
Moving to backlog pending further discussion.

**Comment by martinjoconnor** [comment]
Changed title. Note that this is not a solution to the template/element confusion. It is simply a necessary initial step on the way. The edited nested elements will not modify the original imported element. 

Will we support nesting indefinitely or just to one level?

**Comment by willrett** [comment]
similar to #607

**Comment by willrett** [comment]
duplicate of #607
