### ISSUE TITLE
Stuck help text

### ISSUE THREAD

**Issue by kjcollins** [metadatacenter/cedar-template-editor#464]
In the metadata editor, if the help text for a field is viewed and the user exits the editor without saving the instance or clicking anywhere else, the help text stays on screen through the user's workspace and any other template, element, or instance, until the page is refreshed. 

<img width="905" alt="screen shot 2016-07-28 at 4 57 56 pm" src="https://cloud.githubusercontent.com/assets/19827553/17233607/f8d63e20-54e5-11e6-9188-c1d1e43675ab.png">

<img width="933" alt="screen shot 2016-07-28 at 4 58 06 pm" src="https://cloud.githubusercontent.com/assets/19827553/17233612/fe3c08c2-54e5-11e6-80b2-1fa88298db13.png">

<img width="843" alt="screen shot 2016-07-28 at 5 13 38 pm" src="https://cloud.githubusercontent.com/assets/19827553/17233683/b5001b16-54e6-11e6-84e6-63975eabf918.png">

**Comment by martinjoconnor** [comment]
No longer reproducible.
