### ISSUE TITLE
Alphabetically ordered class tree

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-template-editor#467]
If things at the same level in the tree were presented alphabetically it would sure be nice

**Comment by michelleif** [comment]
yes it would. here is an example of classes that appear in alpha order when browsed in BioPortal, but when browsing the same ontology via CEDAR, they are in an unknown order
![CEDARBiblioteko.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/581116c7f17930130007d3eb/125516c66e82c728ace21e0d46cbb1be02b0a1a08de5b64cb058fb9b6b0a65633b0ba92e7391a172fd172d02595f4fac10510d16fcad8a2aa5b63c748b5b03bb827f4366846c4ff8e7df46f554f832815d84b1b68b49c1e9342ce28b874d3b1d030ac4.png)
![BioPortalBiblioteko.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/581116c7f17930130007d3eb/125516c66e82c728ace21e0d46ca9d95138d91bd8ee59d4aa651f99b3d432c7c6b48e13b628ae92dbc56395b4d5a48ff47585e44adf0db79a6e23f71895c0be9d06a5722952f0dbefad341eb5ee779c11ac7a4b6984dc8e23c20e68a86463b1e0d1b81fc5827ed.png)

**Comment by michelleif** [comment]
I tried to label this LD4P but it wouldn't let me.

**Comment by marcosmro** [comment]
Duplicate of https://github.com/metadatacenter/cedar-project/issues/409
