### ISSUE TITLE
Modification timestamp on instances doesn't update in desktop

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-template-editor#477]
I updated and saved an instance, but its modified date didn't change. Tried reloading the page, still no change.

**Comment by egyedia** [comment]
Seems to be a front-end issue. The data on the template server is modified, and it is also shown in the UI if the front-end is refreshed. 
We need to investigate this in detail. There could be a bigger problem in the UI, the JSON viewers are not behaving consistently

**Comment by martinjoconnor** [comment]
As per discussion today, the persisted version is updated properly - only the GUI JSON preview is inaccurate. So not a killer bug -  but definitely worth trying to fix.
