### ISSUE TITLE
Spreadsheet row addition fails

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#479]
Can add a row to a spreadsheet view in the metadata editor but the new row is not reflected when the view mode is switched back to the standard view.

**Comment by egyedia** [comment]
Currently the right click for adding a row or column is disabled - it is like this from the beginning of the integration.

However, it is possible to add new rows/columns using the "fill handle" - the small rectangle in the lower right corner of a cell, which can be dragged.
This indeed causes malfunctioning of the spreadsheet view.

There is a solution for this, but unfortunately works only with handsOnTable versions 0.23.0 and upwards. We have 0.19.0 integrated.

A decision should be made, we should see how much time we want to allocate to this task.
If there are no compatibility issues, this could be fixed under 1 hour with the upgrade of the plugin, performing some checks, and committing the changes.

If there are complications, this could lead to a lot of work.

This is the documentation of the feature:
https://docs.handsontable.com/pro/1.6.0/Options.html#fillHandle

This is the ChangeLog. We should see which version we want/can upgrade to:
https://github.com/handsontable/handsontable/releases

It seems that some of the latest releases have breaking changes. 
We should talk about this tomorrow.

**Comment by martinjoconnor** [comment]
It is reassuring at least to see that this widget is under active development. Yup - as per previous comment - let's discuss and tackle after we have mailed permissions and model updates. Hopefully it will work out of the box.

**Comment by willrett** [comment]
spreadsheet feature hidden for 0.8 release and should be brought back for 1.0
