### ISSUE TITLE
Review/finalize colour scheme

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#486]

**Comment by martinjoconnor** [comment]
@willrett @graybeal  Is this still a thing?

**Comment by graybeal** [comment]
The request was to check the current CEDAR service color scheme against the one we initially developed with Wired Moon; and if it differed, either re-set it to the Wired Moon scheme, or propose a new scheme to the Product Owner. 

(Part of the goal of the original multi-hued color scheme was to provide another clue about whether users are editing templates or metadata.

I have no information on the status.

**Comment by martinjoconnor** [comment]
Is any action needed on this for 1.0?

**Comment by graybeal** [comment]
No action needed for 1.0. You can drop or close this task, it will come again as an issue if it is still an issue.

On Jan 24, 2017, at 4:53 PM, martinjoconnor <notifications@github.com<mailto:notifications@github.com>> wrote:


Is any action needed on this for 1.0?

**Comment by martinjoconnor** [comment]
Closing for the moment.
