### ISSUE TITLE
Model fix tasks for 0.8

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#491]
This task combines all remaining 0.8 bugs and model fixes. It is also linked to the JavaScript model validation library task (#337) and the back end validation task (metadatacenter/cedar-template-server#5).

(1) Our custom _value field should be replaced with the JSON-LD @value field.
See: https://www.w3.org/TR/json-ld/#typed-values. (Previously metadatacenter/cedar-schema-server#2.)

(2) Multiple choice fields are currently encoding options in the _ui field, which is not correct. Task #371 will move these to the _valueContraint field. We need to update the template schema to reflect this. (Previously #463).

(3) A field title saved in the element designer appears as "untitled" (instead of the saved name) in the element JSON. "untitled" name inherited by a template that uses that element. Previously (metadatacenter/cedar-project#66)

(4) The options specified for a pick from a list field are stored in an options field in the _ui field. These should be stored in the _valueConstraints field because they are part of the specification - they are not just rendering choices. We will need a new field in the _valueConstraint field to specify these options. The selectionType option should also be in the _valueConstraints field. (Previously #371.)

(5) Currently, if a template has some static fields (e.g. video, static text), all instances of the template will contain those static fields too, with an empty _value field inside. Example: "video": { "_value": "" }

The purpose of static fields is just to provide some static content to guide users when filling out the template. Those fields cannot be filled out, they cannot contain metadata values. As a consequence, those fields should not be added to template instances. (Previously #222)

(6) Fields deleted in editor remain in template. (Previously metadatacenter/cedar-project#21)

(7) Some field names are stored as UUIDs. In spreadsheet mode this UUID is displayed instead of the field name. (Previously #318).

(8) Multiple instance text fields not stored correctly in JSON. See #175.

(9) Front allows invalid names for fields. e.g., ".." (Previously metadatacenter/cedar-template-server#9.)

(10) Strip _tmp fields from JSON before saving to server. (Previously #193)

**Comment by marcosmro** [comment]
Pending fixes (6, 7, 9) have been moved to #531
