### ISSUE TITLE
JSON shown on the UI does not correspond to the JSON stored in MongoDB

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-template-editor#495]
When opening a template, element or instance on the template editor, the JSON shown when clicking on the top-right icon is different from the JSON stored in the MongoDB database.

**Comment by martinjoconnor** [comment]
@marcosmro Is this still true?

**Comment by marcosmro** [comment]
Yes. Sometimes, the JSON shown does not correspond to the JSON stored in the database and it is necessary to refresh the page.

**Comment by willrett** [comment]
will be addressed by continuous save
