### ISSUE TITLE
Sorting workspace by date returns zero results

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-template-editor#496]
Click on the sort tool in the toolbar of the workspace.  Select recently created or recently modified.  No results are returned.

**Comment by martinjoconnor** [comment]
Assigned these search issues to Atti instead of Marcos.

**Comment by martinjoconnor** [comment]
Merged into metadatacenter/cedar-project#89

**Comment by martinjoconnor** [comment]
Merged into metadatacenter/cedar-project#89
