### ISSUE TITLE
Validation of schemas

### ISSUE THREAD

**Issue by agbeltran** [metadatacenter/cedar-template-editor#502]
I was checking the JSON-schemas available at:
https://github.com/metadatacenter/cedar-template-editor/tree/develop/app/resources
and I am having some problem validating these two schemas:
1. field-empty.json due to 

```
 "@value": {
      "type": null
    },
```

(lines 39 to 41)
2. field-static-empty.json due to all the ocurrences of 'null':

```
"_content": null
  },
  "required": [
    "_content"
  ],
  "pav:createdOn": null,
  "pav:createdBy": null,
  "pav:lastUpdatedOn": null,
  "oslc:modifiedBy": null,
  "additionalProperties": false
```

Should they be "null"? Thanks

**Comment by martinjoconnor** [comment]
No longer nulls in latest code.
