### ISSUE TITLE
Make return key close some popups

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#505]
Some popups could be closed via the return key (assuming valid content) instead of requiring the pressing of the Save button, e.g.,

**Comment by martinjoconnor** [comment]
<img width="429" alt="screen shot 2016-09-12 at 6 56 07 pm" src="https://cloud.githubusercontent.com/assets/1731323/18458979/d1f1c1b8-791a-11e6-9777-b6da7f9d8924.png">

**Comment by willrett** [comment]
The rename dialog closes on enter.  I don't see any other dialogs that can be closed with an enter key.    Move and Share are not appropriate for closing on enter.  You can close on enter for dialogs that have a field you are typing into.  Please let me know if you have any others.
