### ISSUE TITLE
Unify the label and description display for fields

### ISSUE THREAD

**Issue by egyedia** [metadatacenter/cedar-template-editor#51]
show the label above the field
show the description in the help box
as placeholder, show dateformat, or phone format, or some generic text

**Comment by marcosmartinezromero** [comment]
For basic text fields, showing both the label above and the label inside the field may be too redundant. 
We need to think about a good way of showing the labels for all field types and elements, either they are multiple instance or not. Also,  for some fields (e.g. date) it would be helpful to have some generic help text, as Atti mentioned (e.g. MM/DD/YYYY)

**Comment by martinjoconnor** [comment]
Will be addressed by new forms.
