### ISSUE TITLE
Resource Move To menu item should be greyed for read only resources

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#512]
<img width="234" alt="c5b433d4-79ad-11e6-9fff-6d386538d727" src="https://cloud.githubusercontent.com/assets/1731323/18488905/4d0c55f8-79b0-11e6-970d-09ee3dd8e074.png">

**Comment by martinjoconnor** [comment]
Ditto for Rename and Delete.

When we implement limited sharing the Share item should also be greyed out.

**Comment by graybeal** [comment]
Is our copy capability also implemented with move option? If so we'll need to add it separately.

**Comment by martinjoconnor** [comment]
Created metadatacenter/cedar-template-editor#511 for Copy To.
