### ISSUE TITLE
Missing help text on some workspace icons

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#523]
Some icons have help text but the sausages, the sort and the profile do not.

<img width="345" alt="screen shot 2016-09-13 at 3 15 19 pm" src="https://cloud.githubusercontent.com/assets/1731323/18493368/15d88420-79c5-11e6-9718-07244b5a1d6f.png">

**Comment by willrett** [comment]
The two buttons without tooltips are on the ellipsis and the sort.  Both of these result in a menu drop down for more choices.  Showing a tooltip would overwrite the menu.  It would be drawn on top of the menu and could obscure it.  Therefore I left them off these buttons.

**Comment by martinjoconnor** [comment]
The tooltip should not interfere with the action. See enclosed showing Gmail tool tips on drop down items.

[QuickTips.mov.zip](https://github.com/metadatacenter/cedar-template-editor/files/769707/QuickTips.mov.zip)
