### ISSUE TITLE
Improve visual appearance of Info panel

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#524]
Currently a little sparse looking.

<img width="360" alt="screen shot 2016-09-13 at 3 21 40 pm" src="https://cloud.githubusercontent.com/assets/1731323/18493562/072ea5d4-79c6-11e6-8e85-c2534386d80d.png">

**Comment by willrett** [comment]
we should display sharing state.

**Comment by martinjoconnor** [comment]
Will be tackled by:

https://github.com/metadatacenter/cedar-template-editor/issues/719
https://github.com/metadatacenter/cedar-template-editor/issues/720
