### ISSUE TITLE
Model bug fixes

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-template-editor#531]
(1) Fields deleted in editor remain in template. (Previously metadatacenter/cedar-project#21)

(2) Some field names are stored as UUIDs. In spreadsheet mode this UUID is displayed instead of the field name. (Previously #318).

(3) Front allows invalid names for fields. e.g., ".." (Previously metadatacenter/cedar-template-server#9.)

(4) The "required" field sometimes has duplicates (which confused some validators, e.g., http://www.jsonschemavalidator.net/).

Related to #5

**Comment by martinjoconnor** [comment]
See also metadatacenter/cedar-model#1

**Comment by martinjoconnor** [comment]
See also  metadatacenter/cedar-project#185.

**Comment by martinjoconnor** [comment]
See also metadatacenter/cedar-template-server#29..

**Comment by rdshankar** [comment]
Do we have a fix for the bug.. field names as UUIDs?

**Comment by martinjoconnor** [comment]
No - it is an open issue. However, these extra fields should have no
practical effect so can be ignored until we remove them.

**Comment by martinjoconnor** [comment]
We cannot reliably reproduce the UUID issue - but somehow fields get internally named using UUIDs. The displayed field name is correct.

**Comment by martinjoconnor** [comment]
Also cannot reliable reproduce (5) above, but should be easy to ensure that the required field is a set and not a list.

**Comment by martinjoconnor** [comment]
Merged into metadatacenter/cedar-project#185
