### ISSUE TITLE
Investigate embeddable forms

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#544]
Investigate allowing CEDAR forms to be embedded in other web pages.

The Stanford AMP group is particularly interested in having this.

**Comment by martinjoconnor** [comment]
A more advanced form of embedding would support a 'headless' mode where the final filled in form is not sent to CEDAR servers and can instead be extracted by the front end application that embeds the form.

**Comment by martinjoconnor** [comment]
Comes up repeatedly.

**Comment by willrett** [comment]
Rewrite the metadata editor as an Angular 7 component which can be published as Node package.

**Comment by cedaradmin** [comment]
Angular 7 task here: metadatacenter/cedar-template-editor#861
