### ISSUE TITLE
Allow ontology constraints to be permanent

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-template-editor#554]
When user indicates they want to select a term from particular ontology(ies), allow them to check a box to remember the constraint.

Reference also https://github.com/metadatacenter/cedar-template-editor/issues/552

**Comment by martinjoconnor** [comment]
Addressed bu #614

**Comment by graybeal** [comment]
LD4P requests in email Aug 1 2017: "if you get a bunch of results when you go to select a class or property, it would be helpful to be able to sort them using the column headers to easily find what you want."
