### ISSUE TITLE
Missing UI feedback for moving template/element

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-template-editor#559]
When I moved a template/element to a folder, the template/element didn't disappear immediately from the screen. It will disappear but after I refresh the browser.

**Comment by martinjoconnor** [comment]
Could not reproduce. Is this still the case on staging? We fixed a possibly related bug a few days ago. Can you post steps to reliably reproduce if the bug is still there.

**Comment by johardi** [comment]
It works now
