### ISSUE TITLE
More narrative values in "Created" and "Modified" columns (e.g., '5 minutes ago', '2 days ago')

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-template-editor#562]
They are easier to read and you can immediately sense the period of time compared to the full date-time information. Perhaps the full date-time info will suit better if the template/element has gone stale.

**Comment by martinjoconnor** [comment]
@willrett, what do you think? Looks interesting. Putting in 1.6 so that we look at soon.

**Comment by michelleif** [comment]
Also be consistent about "modified" vs "updated". If you sort by "Recently Updated" then you are sorting the "Modified" column. Should be "Recently Updated" and "Updated" or "Recently modified" and "Modified".

**Comment by willrett** [comment]
Yes, this is a good idea and we should do it.

**Comment by willrett** [comment]
I changed the date display to show only time if date is today and not show year if date is current year.  This is not as fancy as suggested here, but a big improvement.  Also sort labels consistent with table headers.
