### ISSUE TITLE
Deleted template fields (or elements) are not immediately removed from the JSON text 

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-template-editor#563]
There are two places where the entries of the deleted fields should be removed as well:
- `#/properties/@context/properties`,
- `#/properties/@context/required`

**Comment by martinjoconnor** [comment]
I think this is a duplicate of a subtask in metadatacenter/cedar-project#185.

@marcosmro Can you verify.

**Comment by marcosmro** [comment]
Thanks right. It's a duplicate of (3) in metadatacenter/cedar-project#185
