### ISSUE TITLE
Missing element title and description when using the template element

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-template-editor#564]
For example,
I have a template element called Person with some relevant fields. And then I want to create a template that requires two Person elements to input the president and the vice-president. When I added these elements to the template design, I didn't find the option to add element title and description (such that I can write the label title "President" and "Vice-President").

This is in contrast with most of the template fields--e.g., Text, Date, Numeric--that they have the field title and description for their GUI presentation.

**Comment by martinjoconnor** [comment]
This will be handled by the properties work that we will be doing soon (by end of April; driven in short term by  LD2P library work). Requirements are linked to in the following task: metadatacenter/cedar-project#283 (though they don't actually explicitly mention this feature). 

I have not extracted the Waffle tasks for the requirements yet. Will leave this open so until I do.

**Comment by martinjoconnor** [comment]
Will be addressed by #34

**Comment by johardi** [comment]
I'm reopening this issue because the fix only implemented the missing title. I think to have a way to add the element description (inside a template or other element) will be useful as well.

**Comment by martinjoconnor** [comment]
@willrett , can you see what options are here.

**Comment by michelleif** [comment]
I second this and had the exact same need today to use an element twice in one template, but give it a different description/help text each time.

**Comment by willrett** [comment]
This means that the property labels need to add a description field.

"propertyLabels": {
      "President": "President",
      "Vice-president": "Vice-president"
    }

**Comment by willrett** [comment]
User can edit the title, description and property of an element in a template.
