### ISSUE TITLE
Back button & arrow dump to home directory from nested folders

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-template-editor#568]
Steps to reproduce:
1. Open an existing element inside a folder (e.g., Home > My Project > Project1)
2. Do nothing or do some editing,
3. Click on the back button.
I arrived at the home directory instead of going back to Project1 folder. The back button will send me to Project1 folder if it comes from a newly created element.

**Comment by willrett** [comment]
duplicate of 282 which is fixed but still needs to be moved to staging

**Comment by martinjoconnor** [comment]
It's back! Happens from both Template Creator and Metadata Editor pages.

**Comment by martinjoconnor** [comment]
Can not reproduce with latest 0.9.4 on staging.
