### ISSUE TITLE
Template field selection menu got overlapped by date fields

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-template-editor#569]
See the screenshot below:
<img width="1094" alt="screen shot 2017-02-13 at 10 24 48 pm" src="https://cloud.githubusercontent.com/assets/5062950/22917747/7484f866-f23b-11e6-9996-6276caa7ded8.png">

**Comment by martinjoconnor** [comment]
Can you send the URL of a template where this happens.

**Comment by johardi** [comment]
I've shared you the template. If you scroll up and down the page, you'll see the overlapping will happen when the menu is in the "detach" mode.

**Comment by martinjoconnor** [comment]
Can you send the URL. (Just cut and paste from URL bar.)

**Comment by johardi** [comment]
https://cedar.metadatacenter.net/templates/edit/https://repo.metadatacenter.net/templates/2e32de86-0a79-49f1-b7dc-98bd26281d9d?folderId=https:%2F%2Frepo.metadatacenter.net%2Ffolders%2Fd79a01f1-7fc8-409e-b78a-f21d325d1a02

**Comment by martinjoconnor** [comment]
Thanks. I've added this to 1.0 bugs.

**Comment by martinjoconnor** [comment]
Behaviour no longer there.
