### ISSUE TITLE
Suggestion: Having a template field for resource identifier

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-template-editor#573]
In particular to enter IRI value that identifies or locates resources (e.g., template instances, concepts, links, etc.)

**Comment by martinjoconnor** [comment]
We will add an initial version of this for the library LD4P project. I'll link this as soon as I have created all the necessary tasks.

**Comment by martinjoconnor** [comment]
Tackled by:

https://github.com/metadatacenter/cedar-template-editor/issues/588
