### ISSUE TITLE
Incorrect value rendered for checkbox fields

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-template-editor#584]
The model is correct, but the value shown on the UI is wrong. See the following screenshots:
![screen shot 2017-02-28 at 2 51 35 pm](https://cloud.githubusercontent.com/assets/7634440/23438119/7defaef6-fdc5-11e6-9ade-70e8eb216e64.png)

![screen shot 2017-02-28 at 2 52 22 pm](https://cloud.githubusercontent.com/assets/7634440/23438127/89554d46-fdc5-11e6-9020-93efc8a9d6c7.png)

**Comment by martinjoconnor** [comment]
Adding to 1.05

**Comment by martinjoconnor** [comment]
Merged into #362
