### ISSUE TITLE
Annotate templates and elements with controlled terms

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#586]
Attach a controlled term to a template or element and reflect in instance.

Needed for 1(a) here:

https://docs.google.com/document/d/1Qs-t3_BN5-Ktspfb7A51a_Hj-rZX9P0T9T29TpJZkCM/edit

**Comment by willrett** [comment]
just one term or can we have multiple controlled terms?

**Comment by martinjoconnor** [comment]
We can have multiple. JSON-LD will support that.

Note that it will not support multiple property annotations, which will be relevant for the property tasks.
