### ISSUE TITLE
Support property relationships in Template Creator

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#587]
Allow template creator to specify property relationship between enclosing template/element and field/element.

Fully supported in model, but not by front end.

Needed for LD4P tasks 1(b, d):

https://docs.google.com/document/d/1Qs-t3_BN5-Ktspfb7A51a_Hj-rZX9P0T9T29TpJZkCM/edit

Dependent on BioPortal task #342, and related to tasks #340, #341.

**Comment by martinjoconnor** [comment]
The basic property search dialog task (#593) and property tree dialog task (#594) will provide dialog to be used to search for properties.

**Comment by willrett** [comment]
library feedback: 
add double-click to select class, property, and value sets
remember your ontologies that you narrowed your results to
