### ISSUE TITLE
Multi-instance element cloning

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#589]
In a multi-instance element, allow element instance and any completed values it contains to be cloned - thus generating a new element instance with all completed values copied.

Necessary for AIRR submissions where 30+ samples are common and only one or two field per sample differ. Likely of very general use.

**Comment by martinjoconnor** [comment]
It turns out that cloning is already the default behaviour for multi-instance elements! (Though the first element is cloned, not the current one.) 

So in the very short term the current system should work for Yale for experimentation.

We still should have a 'create empty' - and change the behaviour to clone from the currently open element.

**Comment by graybeal** [comment]
Please see also https://github.com/metadatacenter/cedar-project/issues/402 for discussion of representation of 'element instance' as a single line in the UX (might make more approaches possible, if you like the general idea)
