### ISSUE TITLE
Values are not appearing in the instance page

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-template-editor#590]
All values are missing except for the text field and the pick-from-list field. The checkbox field displayed a funny code there.

![screen shot 2017-03-17 at 4 00 37 pm](https://cloud.githubusercontent.com/assets/5062950/24065845/50e79414-0b2b-11e7-8fbc-252293347881.png)

**Comment by marcosmro** [comment]
I'm currently addressing this issue
