### ISSUE TITLE
Client side validation logging

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#592]
Initially we will log all validation errors in the resource server (with the goal of failing the REST on validation errors when we have confidence that we have convergence). However, we would also like to log these errors on the browser Javascript console. 

To do this we can get the server to add a custom header on validation failures containing the failure message, which the client can then log to the console.

**Comment by johardi** [comment]
Related to https://github.com/metadatacenter/cedar-resource-server/issues/25. The custom header is already implemented.

For client-side logging, the front-end could look at headers labeled: "CEDAR-Validation-Status" and "CEDAR-Validation-Report".

Should I include @willrett or @marcosmro to create the client-side logging?

**Comment by martinjoconnor** [comment]
Yes - include both and someone will get to it first.
