### ISSUE TITLE
Display RDF representation of instance in Metadata Editor

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#596]
Using recent REST option to return the RDF representation of an instance (metadatacenter/cedar-project#188), put icon next to JSON icons in Template Editor to toggle RDF instance diaplay.

**Comment by martinjoconnor** [comment]
Use the following RDF icon:

![screen shot 2017-03-26 at 8 50 26 pm](https://cloud.githubusercontent.com/assets/1731323/24340311/0884cb64-1266-11e7-9f72-18a4eee3fe93.png)

**Comment by willrett** [comment]
using client side RDF conversion in document preview
