### ISSUE TITLE
Use standard icons for JSON Schema, JSON LD, RDF

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#597]
In template editor use standard icons for JSON Schema, JSON-LD, and RDF (#596) display.

**Comment by martinjoconnor** [comment]
Use the following icons for JSON Schema, JSON LD, and RDF, respectively:

![screen shot 2017-03-26 at 8 49 10 pm](https://cloud.githubusercontent.com/assets/1731323/24340348/4f4ba4b4-1266-11e7-8dad-57159560e106.png)

![screen shot 2017-03-26 at 8 50 00 pm](https://cloud.githubusercontent.com/assets/1731323/24340380/870ec3c2-1266-11e7-8589-9dbc49cbfa7f.png)


![screen shot 2017-03-26 at 8 50 26 pm](https://cloud.githubusercontent.com/assets/1731323/24340349/5288677a-1266-11e7-936f-5acddd96321c.png)

**Comment by willrett** [comment]
Where do I find the JSON Schema icon, and where would it be displayed in the UI?  I updated the document preview to use the other two icons.

**Comment by martinjoconnor** [comment]
There is a big one here: https://avatars2.githubusercontent.com/u/2182898?v=3&s=400

It would be used for template or element JSON, which are represented using JSON Schema - unlike instances, which are represented as JSON-LD.

**Comment by willrett** [comment]
Yes, I saw that but it is a png with a white background and our other fonts are SVGs with transparent backgrounds.

**Comment by martinjoconnor** [comment]
Perhaps @egyedia can do some Photoshop magic with it?
