### ISSUE TITLE
Instance rendering issues

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#609]
Rendered instances seem to be missing labels in some situations.

For example, see:

https://cedar.staging.metadatacenter.net/instances/edit/https://repo.staging.metadatacenter.net/template-instances/993c7aba-9182-4667-ba6c-78cc9c3eca85?folderId=https:%2F%2Frepo.staging.metadatacenter.net%2Ffolders%2Ff77e5f5e-0bce-4e52-8415-a684614b9461

<img width="846" alt="screen shot 2017-04-13 at 11 21 13 am" src="https://cloud.githubusercontent.com/assets/1731323/25001105/c3dbfe4a-203b-11e7-8a88-3f92956a911e.png">

**Comment by martinjoconnor** [comment]
The associated template seems to have missing names for some enclosed elements:

https://cedar.staging.metadatacenter.net/templates/edit/https://repo.staging.metadatacenter.net/templates/d7c9d050-a4aa-4448-b7ed-cf58b980baf2?folderId=https:%2F%2Frepo.staging.metadatacenter.net%2Ffolders%2Ff77e5f5e-0bce-4e52-8415-a684614b9461

See, for example, the initial project description element, which has no title.

**Comment by willrett** [comment]
This was caused by empty property values.  I am now defaulting to 'default'.  I don't have the original element name available.  It gets wiped out when the user enters a property.  So the default has to be some fixed value.
