### ISSUE TITLE
Refresh the JSON-LD tab when updating an instance

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-template-editor#633]
For templates or elements that contain multiple cardinality nested elements, users may need to open an existing instance (e.g., principal investigator) and add new element instances to it (e.g., address). The @id's for these new element instances are generated by the backend and returned to the UI. The JSON tab should be updated with the updated instance, which contains the element instance @id's generated by the backend.

**Comment by willrett** [comment]
Not sure what this means.  Please give an example.

**Comment by willrett** [comment]
the JSON-LD display is kept up-to-date
