### ISSUE TITLE
Unable to annotate the property name that came from an element

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-template-editor#638]
To reproduce:
1. Create an element, say "Person",
2. Create a template (or an element), say "Study",
3. Add the "Person" element into the template and click on the 'Add Property' RDF-icon. Select a row and click OK,
4. Nothing happened.

**Comment by willrett** [comment]
This should be hot-fixed in the current release.

**Comment by martinjoconnor** [comment]
Regression test task: #645

**Comment by johardi** [comment]
Update: I noticed that the annotation actually got stored in the JSON document, but the UI didn't behave properly
