### ISSUE TITLE
Tag CEDAR requests to BioPortal

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-template-editor#646]
Tag CEDAR requests made to the BioPortal system, so that they can be recognized as CEDAR requests, at least via the BioPortal logs. Consider associating them with individual deployments, so that we can tell if multiple copies of a deployment are being used by different clients.

**Comment by martinjoconnor** [comment]
How does this tagging work? API keys are generally the solution here.

**Comment by graybeal** [comment]
Yeah, that's the general solution. (BTW, should have said "Consider this", not implied "do this.")

My worry is how to make sure we can tell what traffic is coming from CEDAR instances. But I think that greater objective can be achieved by just making sure we can associate the keys with CEDAR instances. Which to me implies we have to define the accounts (and associate them with appropriate end users of CEDAR), rather than letting users do so.

**Comment by graybeal** [comment]
What was the final answer as to how we'll tell what traffic is coming from CEDAR instances?
