### ISSUE TITLE
Element fields not displaying initially in multi-instance mode

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-template-editor#647]
The error screenshot:
![screen shot 2017-05-15 at 2 33 57 pm](https://cloud.githubusercontent.com/assets/5062950/26080571/0e51d8ec-397c-11e7-85a7-37acbe1e4a98.png)

The fields will finally appear if you first click (+) Add and then select the next entry.

**Comment by johardi** [comment]
Access to the example: https://cedar.metadatacenter.net/dashboard?folderId=https:%2F%2Frepo.metadatacenter.net%2Ffolders%2F9929001f-bfd6-44e6-85db-75379427904d

**Comment by martinjoconnor** [comment]
Related to (but not same as #643).

**Comment by martinjoconnor** [comment]
Associated regression test: #648
