### ISSUE TITLE
Support hidden field values in instances

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#656]
Using pre-filled field values (#655) let template designer specify that fields are not visually rendered in Template Editor but appear in instances.

**Comment by martinjoconnor** [comment]
Will require model update. Initial suggestion: UI field with two new fields: ```default```, which is an optional field that stores a string value, and ```hidden```,  which is a boolean field. Hidden only makes sense when a default is present.

**Comment by marcosmro** [comment]
Here is an example that shows the proposed model updates to support hidden fields, as well as fields with default values:

<pre>
"_ui": {
        "title": "Study ID",
        "description": "Study identifier",
        "inputType": "textfield",
        <b>"hidden": true</b>
        },
 "_valueConstraints": {
        "requiredValue": false,
        <b>"defaultValue": "S001"</b>
        }
</pre>
