### ISSUE TITLE
Allow JSON field names to contain any valid characters

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#659]
We should allow JSON field names to contain any valid JSON characters. Currently, we take the display name for a field and strip it to contain only alphanumerics, which is unnecessary.

**Comment by martinjoconnor** [comment]
See also: https://github.com/metadatacenter/cedar-model-validation-library/issues/36

**Comment by martinjoconnor** [comment]
Josef did some digging and discovered that JSON is very promiscuous here to we should not be quite be so restrictive. In some cases (eg.., ImmPort) the user may require a particular JSON field name in the instance so we should support any valid JSON field name.

**Comment by johardi** [comment]
Closes via https://github.com/metadatacenter/cedar-model-validation-library/commit/0091cf34b1dba87caa76bd24482339a9bd035269 and https://github.com/metadatacenter/cedar-model-validation-library/commit/99cc1cfe5962a531a39ff98d22b0d8b6f855b2d8

**Comment by martinjoconnor** [comment]
We need to check that there are not unintended consequences here. 
Does the front end code still work with these new characters in the field names. (It should.)
Mongo also has some restrictions.

**Comment by martinjoconnor** [comment]
See also #662 (ability to explicitly set instance field names)

**Comment by martinjoconnor** [comment]
Possibly trivial but too risky for the moment. Moving to 1.5.

**Comment by martinjoconnor** [comment]
Possibly related: Certain field names can break stuff, e.g., www.google.com

**Comment by martinjoconnor** [comment]
We will have to update the ```patternProperties``` specification in templates and fields - and the mode validator software. Current ```patternProperties``` specification is:

     "patternProperties": { "^(?!pav)(?!schema)(?!oslc)[a-zA-Z][a-zA-Z0-9]*$": { "type": "string", "format": "uri" } },

**Comment by johardi** [comment]
There is a case where the front end is still stipping out the special characters

**Comment by marcosmro** [comment]
I modified the code to allow all characters except for those that are invalid in MongoDB, which are: dot (i.e., .) and dollar sign (i.e., $) at the beginning of the JSON field key. If the user enters a field name that contains any of these characters (e.g., $disease), they will be removed to generate a valid JSON field key (e.g., disease). The field name entered by the user (i.e., $disease) will be stored in the _ui.title field and will be shown on the UI but the JSON field key will only contain valid characters.
