### ISSUE TITLE
Need informative message when no write permission

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#670]
Currently get very dramatic error when attempting to save a resource when write permission lacking. 

(1) Make this error more user friendly.

(2) Think about immediately warning a user when they attempt to modify such a resource

**Comment by willrett** [comment]
The user will see a "lock" icon in the top navigation bar next to the document name.  This indicates that write permission is disabled.  In addition, the save and cancel buttons will not be displayed.
