### ISSUE TITLE
I just changed the template name and lost the complete metadata that I have entered through this template. See attached image

### ISSUE THREAD

**Issue by ahmadchan** [metadatacenter/cedar-template-editor#671]
![cedar1](https://user-images.githubusercontent.com/1532039/28046699-74adbb02-65b3-11e7-9ae9-acc468d3122f.png)

**Comment by martinjoconnor** [comment]
Can you outline the steps to reproduce this. You changed the template name or the instance name?

**Comment by martinjoconnor** [comment]
Cause: editing templates after creating instances from those templates can break instances. As discussed with Ahmad, this is a known problem that we will fix with a warning.

Warning task: https://github.com/metadatacenter/cedar-template-editor/issues/676
