### ISSUE TITLE
I created a directory in my workspace and while sharing I made Martin Owner (Mistakenly). I can not reverse it or delete Martin because now Martin is owner, I just have privilege to read and write. This is abnormal behaviour. Please see the attachment 

### ISSUE THREAD

**Issue by ahmadchan** [metadatacenter/cedar-template-editor#673]
![issue](https://user-images.githubusercontent.com/1532039/28082155-aa2cdbbe-663f-11e7-86ab-586ec3a3e0ec.png)

**Comment by martinjoconnor** [comment]
This is expected behaviour. I will change the ownership to you.

**Comment by martinjoconnor** [comment]
Ownership now changed.

**Comment by martinjoconnor** [comment]
Can you use short titles in your issues. The body can contain the explanation. See example titles here:

https://waffle.io/metadatacenter/cedar-project
