### ISSUE TITLE
JSON is not updating with the change in template

### ISSUE THREAD

**Issue by ahmadchan** [metadatacenter/cedar-template-editor#678]
![json](https://user-images.githubusercontent.com/1532039/28143073-c458e0c6-6731-11e7-86a5-42f72c9a39c5.png)
As discussed with Martin, Organism involved and other new added fields do not appear in the JSON.
here is the instance address https://cedar.staging.metadatacenter.net/instances/create/https://repo.staging.metadatacenter.net/templates/eb8c610c-c4d1-4687-80bb-b980a9fdb9d7?folderId=https:%2F%2Frepo.staging.metadatacenter.net%2Ffolders%2F51efb614-a148-49ee-83f8-b86fe87ede55

Enable JSON and ctrl+F for "organism involved", you will find only organism but not organism involved.

**Comment by martinjoconnor** [comment]
Had just created here: https://github.com/metadatacenter/cedar-template-editor/issues/677
