### ISSUE TITLE
Incorrect version number in entity description field

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#679]
Current version on staging (1.3.1) generates template description fileds with 1.3.0 version number, e.g.,

"T1 with hidden field template schema autogenerated by the CEDAR Template Editor 1.3.0"

Can reproduce by creating a template and inspecting the JSON.

**Comment by marcosmro** [comment]
I've taken a look at this issue and everything seems to work fine. On staging the metadata editor is generating "... element schema autogenerated by the CEDAR Template Editor 1.3.3-SNAPSHOT" both for elements and templates. The CEDAR version is read from the CEDAR_VERSION environment variable. We just need to remember to update that variable when a new version is deployed to staging/production.
