### ISSUE TITLE
Issue with saving template

### ISSUE THREAD

**Issue by agbeltran** [metadatacenter/cedar-template-editor#681]
After creating a template and saving it, when trying to go back (clicking the arrow at the top left of the screen), I get a dialog box asking "Are you sure? Your recent changes will be lost" (even if it was just saved).

**Comment by martinjoconnor** [comment]
Duplicate of #508

**Comment by agbeltran** [comment]
Hi @martinjoconnor  - #508 is about the sharing templates functionality. Maybe you meant it was a duplicate of another issue?

**Comment by martinjoconnor** [comment]
You are right. Wrong 508: https://github.com/metadatacenter/cedar-project/issues/508

**Comment by agbeltran** [comment]
ok, thanks! the cedar-project repository has the issues that apply for all tools, I guess?

**Comment by martinjoconnor** [comment]
Yup.  We are not religious about  it, but we try to put tasks in relevant repos (cedar-metadata-editor for front end issues, for example). When in doubt, cedar-project works.
