### ISSUE TITLE
cannot delete fields when editing an Element

### ISSUE THREAD

**Issue by michelleif** [metadatacenter/cedar-template-editor#684]
Create an Element.
Adda text field.
Try to delete the field using the X in upper right-hand corner. The X doesn't do anything.
Tried to delete a field from a Template and it worked fine.
Tried on Mac on both Safari and Firefox. Tried on other Templates and other fields, same problem.

**Comment by marcosmro** [comment]
Duplicate of https://github.com/metadatacenter/cedar-project/issues/513. The fix will be released to production tomorrow.
