### ISSUE TITLE
Image and rich text fields no longer working

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#686]
Nothing appears in the Metadata Editor for these static field types.

**Comment by graybeal** [comment]
@martinjoconnor Did you intend they be visible in the instances too?  I seem to remember a discussion along these lines. It would be super-nice to have the HIDDEN option control whether they were template-only, or also visible in the form being filled out (so, could be used for instructions, context, etc.).

**Comment by martinjoconnor** [comment]
They were only ever visible in instances. We never had these for templates.

This is the task for that template fields: 

https://github.com/metadatacenter/cedar-project/issues/400

(I renamed to reflect what I think was intent.)

**Comment by graybeal** [comment]
I am confused. You say "They were only ever visible in instances". I used the rich text field in a template 3 months ago to do a demo. See the screenshot below, showing it displayed in the template editor. I actually wanted it in an instance but I couldn't make that work.

![cedar_02](https://user-images.githubusercontent.com/1266896/29650524-5c16d76c-8850-11e7-868d-79ea66e8b408.png)

**Comment by martinjoconnor** [comment]
I guess that must have been a preview mode - or I am completely misinterpreting how these worked.

@willrett, can weigh in here.

**Comment by graybeal** [comment]
As you say, the task for the template (The task for the template (https://github.com/metadatacenter/cedar-project/issues/400) reflects what I hoped was the original intent. That task, written while I was using them, reflect what I was saying above -- they never worked for instances. (Well, never say never. At least for a long time they haven't). 

(And now they don't work for templates either, see https://github.com/metadatacenter/cedar-project/issues/560.)

**Comment by michelleif** [comment]
The Rich Text field still doesn't work. I added one to a template called "Fun for Testing!" (which is shared with CEDAR Dev Team), and when I tried to populate the template / create an instance, my rich text field does not appear.
