### ISSUE TITLE
JSON not displaying for some  templates

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#699]
Try with following template:

https://cedar.staging.metadatacenter.org/templates/edit/https://repo.staging.metadatacenter.org/templates/02a9930b-c621-41fe-bf1c-8b9e73552248?folderId=https:%2F%2Frepo.staging.metadatacenter.net%2Ffolders%2Fdf05e97f-3765-4102-afae-b94b8996cb1d

**Comment by willrett** [comment]
I see JSON in the panel  and am getting validation errors.  Is the JSON incorrect?

**Comment by martinjoconnor** [comment]
I'm seeing it now. Perhaps a cache issue. 

Yes, this has a validation issue (and I will be patching shortly).
