### ISSUE TITLE
Warn about 'click plus to share' 

### ISSUE THREAD

**Issue by graybeal** [metadatacenter/cedar-template-editor#709]
8) I tried to share my template. I started typing a name, and selected the person and clicked Done. I didn’t know I had to click the + sign. I thought the + sign was if I needed to add an additional person. If you select a person, and don’t click the + , and then you click Done, CEDAR doesn’t warn you that you didn’t actually add the person.

From LD4P email 8/1/2017

**Comment by michelleif** [comment]
Please fix this. I was just working with a user. I messaged them this "can you share your form with me so I can try it? in your workspace, right-click your form and choose share, then find my name, then click plus, then save"
I couldn't find the shared item in "Shared with Me". I asked the user to check again if it was shared. It was not, because she hadn't done the Plus thing. Even with that pre-instruction. This wastes a lot of user time. Thank you!

**Comment by willrett** [comment]
I made some changes in #641 which address this problem.  Please let me know if you think these changes do not fix the issue.

**Comment by michelleif** [comment]
This does not seem to be fixed. I just tried this on staging, tried to share a resource with a person, found the person's name and clicked it, then clicked DONE, and the window closed without warning me that I hadn't clicked the plus sign and therefore hadn't shared the thing with the person.

**Comment by willrett** [comment]
Hi Michelle,


I did not fix this by disabling clicking DONE.  The fix that I put in is to make it more apparent to teh user that the selected user has not yet been added.


Debra



Debra Willrett

Senior Software Developer, Research

Stanford Center for Biomedical Research | Stanford University

Medical School Office Building | 1265 Welch Drive, X207

Stanford, CA 94305

http://metadatacenter.org

________________________________

**Comment by graybeal** [comment]
So for now, I propose we leave this as implemented, to see if the problem 'goes away'. If it doesn't, we can come back and do the check-if-really-DONE validation.

**Comment by michelleif** [comment]
or even better would be like Google (sorry) where you select the person(s) to share with, you select what kind of sharing (read/write), then you click OK and you're done.

**Comment by michelleif** [comment]
Real life user experience from today.
Me: Kim, can you share your folder with Josh?
Kim: sure. Josh, I shared my folder with you.
Josh: I can't see it.
Me: Kim, you have to be sure to click the plus sign next to the person's name when you share with them.
Kim: ok, let me try that
Josh: I can see it now!

**Comment by graybeal** [comment]
It appears this did not fix the issue, at least 3 people are still reporting it. I'm going to reopen so we can revisit.

**Comment by willrett** [comment]
Fixed by removing pluses and using an ok, cancel instead.  This should make it very clear that you have something to do to complete the action.
