### ISSUE TITLE
Add publish button to Template, Element, and Field Designer and Workspace

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#715]
Add publish button to Template, Element, and Field Designer and Workspace to publish draft. Button greyed out if artifact not in draft stage. Prompt user for version number (#716). Call publish endpoint after getting version (https://github.com/metadatacenter/cedar-template-server/issues/47).

UI2b in https://docs.google.com/document/d/1E-u8zdq9oX5XL1OlZk28g47FlUgljFK-ubfxeSwGd8s/edit#

Requires #716

**Comment by willrett** [comment]
fixed in feature/versioning branch
