### ISSUE TITLE
Workspace filtering of templates and elements  by version and publication status

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#717]
Add facet filter on left side of workspace to allow user to view (1) only latest version or all versions, and (2) only published or drafts or all. Calls updated folder content endpoint (https://github.com/metadatacenter/cedar-template-server/issues/48).

UI3 in https://docs.google.com/document/d/1E-u8zdq9oX5XL1OlZk28g47FlUgljFK-ubfxeSwGd8s/edit#

**Comment by willrett** [comment]
fixed in feature/versioning branch
