### ISSUE TITLE
UTF-8 character issue with KeyCloak registration

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#721]
Possible internationalization issue:

https://cedar.metadatacenter.org/dashboard?folderId=https:%2F%2Frepo.metadatacenter.org%2Ffolders%2F4aae0ac1-e513-467a-b4d3-982aeecefd90

<img width="316" alt="screen shot 2017-11-21 at 9 51 10 am" src="https://user-images.githubusercontent.com/1731323/33088149-a63f4e4a-cea1-11e7-8bdf-2ab03d12e316.png">

**Comment by willrett** [comment]
This is a UTF-8 character set issue.  It with user names, so the problem is likely to be the registration via KeyCloak.  The template editor has UTF-8 charset on all html files.  Entering UTF-8 into a template editor field will display the UTF-8 characters correctly.

**Comment by graybeal** [comment]
This problem appears to be fixed, no users are showing issues like this.
