### ISSUE TITLE
Obscured help text in Template Editor

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#722]
Template help text can be partially obscured by header in some situations in Template Editor .

To reproduce, click on help text for the following template:

https://cedar.staging.metadatacenter.org/instances/edit/https://repo.staging.metadatacenter.org/template-instances/8b14094b-67a6-492b-8520-5373d7859cbd?folderId=https:%2F%2Frepo.staging.metadatacenter.net%2Ffolders%2F76bbbd4c-8170-4841-aba1-3953a8f8a12b&search=cairr&t=1511209128278

<img width="273" alt="screen shot 2017-11-21 at 1 54 36 pm" src="https://user-images.githubusercontent.com/1731323/33098947-f57d1010-cec3-11e7-9695-80d785606399.png">

**Comment by willrett** [comment]
fix: added tooltip-append-to-body=true to toolbar tooltips
