### ISSUE TITLE
Difference between required property in UI and generated json schema

### ISSUE THREAD

**Issue by agbeltran** [metadatacenter/cedar-template-editor#723]
I created a very simple template element with a single property "name". The property is of type text and it is not required. 
However, the JSON schema generated includes the property as required:
```
 "required": [
        "name"
      ]
```
I would have thought that "required" should be empty - or not?
Thanks

**Comment by agbeltran** [comment]
I should have added that the JSON schema generated is the same if the property is set as required, so it looks like it is always being set as required in the JSON schema.

**Comment by martinjoconnor** [comment]
We force instances to contain all fields specified in the associated template. When no value is supplied for a field its value should be a JSON object that contains an ```@value``` field with a value of ```null```.

For example, a text field called ```name```  with no value should look as follows in the instance:

```
"name": {
  "@value": null
}
```

CEDAR's required logic operates outside of JSON Schema.  If a field is required then its instance must not have ```null``` as a value for its ```@value``` field.

**Comment by agbeltran** [comment]
thanks for clarifying @martinjoconnor; I've noticed now that the difference at the schema-level is at:
```
 "_valueConstraints": {
        "requiredValue": true,
        "defaultValue": "sample1"
      },
```

**Comment by martinjoconnor** [comment]
Note that there is a wrinkle with URI-valued fields. JSON-LD does not allow the value of ```@id``` fields to be ```null```. For example, the following is invalid JSON-LD:

```
"homepage": {
  "@id": null
}
```

For URI-valued fields with no values we simply use an empty JSON object:

```
"homepage": {}
```
