### ISSUE TITLE
Template elements with "minItems": 0 cannot be expanded

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-template-editor#734]
Steps to reproduce:

1) Create an element containing one or several fields.
2) Create a template. Add the element previously created to it and set the minimum cardinality to 'none'.
3) Populate the template and try to expand the element.

I noticed about this issue when trying to populate the BioSample template in production, since the optionalAttribute element has a minimum cardinality of 0. We should't use that template for demos until this issue is fixed.

Link to populate the BioSample template: https://cedar.metadatacenter.org/instances/create/https://repo.metadatacenter.org/templates/f182359b-dbfa-48b7-908d-8bc3c4642cca?folderId=https:%2F%2Frepo.metadatacenter.org%2Ffolders%2F3fc11b1b-85f2-4d89-90a0-48ddd1a912caw

**Comment by willrett** [comment]
fixed in feature/attribute-value-pairs branch
