### ISSUE TITLE
Better error message when opening instance with inaccessible template

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#739]
Currently, if a user shares an instance with a user and does not share the associated template the message that the user will get when trying to open the instance in the Metadata Editor will be a general "no permissions" error. Instead, say something more specific, e.g.,

You do not have permissions to view the template that was used to generate this instance

**Comment by willrett** [comment]
We probably need to use $q.all to make multiple asynchronously promises and not open the instance unless both the instance and the template are available.

**Comment by martinjoconnor** [comment]
Related to https://github.com/metadatacenter/cedar-project/issues/800

**Comment by willrett** [comment]
"Please get read access to the template that was used to generate this instance." 

 It would be nice to have the template name in the error, but all we have is the id at this point.
