### ISSUE TITLE
CDE field selection in Template Designer

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#741]
We will extend the Template Designer (1) to allow users to select a specific CDE from all available CDEs, and (2) to add the selected CDE as a field in a CEDAR template. The Template Designer will use the REST-based search API provided by the CDE microservice (metadatacenter/cedar-cde-server#6) to retrieve CDEs matching a basic search string (metadatacenter/cedar-cde-server#9), presenting basic information about each one. When a user selects a particular CDE, the Template Designer will display a visual representation of the resulting field (see Task 11).

Task 10 in https://docs.google.com/document/d/1Mc0MHJN27AN27eBskPiGnoNZ91yd49EW4UYu3aJSjW4/edit#

**Comment by martinjoconnor** [comment]
Since we are now going to represent CDEs as first class fields the task will differ slightly in that we will instead extend CEDAR's Template Designer to allow search of these fields (in the same way as elements are currently searched for).

**Comment by willrett** [comment]
branch issue/feature-750
