### ISSUE TITLE
CDE field representation in Template Designer

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#742]
We will extend the Template Designer to support CDE-derived fields. As discussed in #741, once a user selects an individual CDE, it will be displayed as a field in the Template Designer. To create this display, the Template Designer will query the CDE microservices REST API (metadatacenter/cedar-cde-server#9)to get the details of the selected CDE. Based on the type of CDE selected, the system will use existing CEDAR field representations to display the CDE using the conversion described in metadatacenter/cedar-cde-server#8 (based on analysis in tasks metadatacenter/cedar-cde-server#2 through metadatacenter/cedar-cde-server#4). For example, if the CDE has a numerical value domain CEDAR's numerical field type will be used to render the selected CDE. CDEs with enumerated values will use CEDAR’s controlled term field type, which provides advanced ontology-based value specification. In some cases, existing CEDAR field types may not be sufficiently expressive to handle the representation of some CDEs and extensions may be required. Tasks 17 through 20 will address these extensions.

Task 11 in https://docs.google.com/document/d/1Mc0MHJN27AN27eBskPiGnoNZ91yd49EW4UYu3aJSjW4/edit#

Field enhancement tasks to support more complex CDE types:

https://github.com/metadatacenter/cedar-template-server/issues/56
https://github.com/metadatacenter/cedar-template-editor/issues/743
https://github.com/metadatacenter/cedar-template-editor/issues/744
https://github.com/metadatacenter/cedar-template-editor/issues/745

**Comment by willrett** [comment]
branch issue/feature-750
