### ISSUE TITLE
Extend datetime field for CDE support

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#745]
The datetime field provided in the Template Designer does not support the variety of temporal representations specified by some caDSR CDEs. Time permitting, we will extend the CEDAR metadata model and implement new field types to support these representations. In particular, we anticipate the implement of new date and time fields to complement the existing datetime field.

Tasks 20 and 24 in https://docs.google.com/document/d/1Mc0MHJN27AN27eBskPiGnoNZ91yd49EW4UYu3aJSjW4/edit#

**Comment by martinjoconnor** [comment]
As per analysis described in #5, we initially will only deal with Date fields so do not need to immediately address Time or Datetime support.

**Comment by graybeal** [comment]
This could be done as a basic implementation focused on a few narrow CDE use cases, which would be useful only for CDE use cases and a few others. Or it could be done in a more systematic way that would address CDE use cases as well as many others.

The earth science community is particularly concerned about formatting date-time the way they want it (which is generally covered by the formats described below).

A few notes for now:
* JSON has data types for a variety of dates and times.
* ISO 8601 provides a complete and recommended standard for displaying dates, times, or dates and times in a 'standard' set of formats. (These formats support separate or joint date and time entries, sort correctly, support partial unit entries (e.g., just hour, hour-minute, hour-minute-second, or hour-minute-floatingPointSeconds), offer time-zone support, and are unambiguously readable.)  There are libraries to support ISO8601. (There is also a time duration format, but that's slightly different.)
* Unix time and supporting libraries give the developer full support using format expressions for configuring presentation or parsing of dates and times, including with short or long textual outputs; making these expressions available to the the template creator is a good way to enable validity checking and meet a full range of user needs.
* There is no clean way of indicating when some sub-fields are not supplied, except by actually having flags indicating whether each sub-field has been supplied. The presentation could and probably should omit sub-fields that have not been supplied, though users might want this option.

**Comment by graybeal** [comment]
See also CEDAR-template-editor#289.

**Comment by graybeal** [comment]
Based on discussions previously with Atti and today with team, the more advanced date-time capabilities should be delayed until we are working on upgrading the UI, which is also a precursor for internationalization, which would be good to incorporate with date-time work.

So this will be an MVP product targeting specifically the needs of the caDSR work.

**Comment by martinjoconnor** [comment]
Duplicate of #289
