### ISSUE TITLE
The value representation for the date field type doesn't follow ISO8601

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-template-editor#748]
The editor produced the output as follows in the JSON-LD document:
```
"Birthdate": {
    "@value": "02/19/2000",
    "@type": "xsd:date"
  }
```
However, the value string does not follow the ISO8601 representation which supposed to be "YYYY-MM-DD"

**Comment by martinjoconnor** [comment]
This is fixed but just missed the last release. Will double check.

**Comment by warzeld** [comment]
I am curioius about this - We don't have a data element with the name "Birthdate", we do have one "Birth Date" 2201154 v1.0. Its true that the display format does not follow ISO8601, as its display format is MM/DD/YYYY - which the date 02/19/2000 appears to follow - but we don't have any data in the caDSR database so where did the 02/19/2000 come from? .
