### ISSUE TITLE
Workspace extensions for 1st class fields

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#750]
Workspace extensions to support 1st class fields.

REST calls defined in: https://github.com/metadatacenter/cedar-template-server/issues/57

and search: https://github.com/metadatacenter/cedar-project/issues/720

**Comment by willrett** [comment]
branch issue/feature-750

**Comment by willrett** [comment]
Tot merged to develop but task is complete
