### ISSUE TITLE
Missing bibo prefix in the @context for multi-value element

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-template-editor#752]

**Comment by willrett** [comment]
I don't see the issue.  There is a bibo property inside items.@conext for an element.

"items": {
        "type": "object",
        "@id": "https://repo.metadatacenter.orgx/template-elements/65d96f6d-d04e-4ad0-a96a-3b580e6b1c6d",
        "@type": "https://schema.metadatacenter.org/core/TemplateElement",
        "@context": {
          "xsd": "http://www.w3.org/2001/XMLSchema#",
          "pav": "http://purl.org/pav/",
          "bibo": "http://purl.org/ontology/bibo/",

**Comment by martinjoconnor** [comment]
BIBO prefix is there.
