### ISSUE TITLE
Shared folder loophole

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-template-editor#755]
Steps to reproduce:
* Login as "User1"
* Create a new folder
* Share the folder with another user "User2" with a write access
* Login as "User2"
* Move the shared folder to User2's workspace
* Login as "User1"
* User1 lost the shared folder

**Expected outcome**: User1 should still be able to access the shared folder because it is shared among the two users.

**Comment by egyedia** [comment]
When you say "User1 lost the shared folder", what do you mean exactly?
I reproduced this on staging. I logged in with User1, went to User2 home folder, and I saw the folder, I created a resource in it.
Where do yo expect to see the shared folder?
Just to be technically correct: User1 owns the folder, the folder is shared with User2 with write access.

**Comment by martinjoconnor** [comment]
As above, this is expected behaviour.
