### ISSUE TITLE
Extend the numeric field UI for adding value constraints

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-template-editor#759]
These value constraints include:
* Min/max value
* Decimal place
* More numeric types, i.e., xsd:float, xsd:double, xsd:int

The model extension is described in https://github.com/metadatacenter/cedar-model-validation-library/issues/81

**Comment by martinjoconnor** [comment]
See also https://github.com/metadatacenter/cedar-project/issues/567
