### ISSUE TITLE
Template created within shared folder is not shared automatically

### ISSUE THREAD

**Issue by agbeltran** [metadatacenter/cedar-template-editor#761]
We found this behaviour:

- Login as "User1"
- Create a new folder
- Share the folder with another user "User2" with a write access
- "User 2" creates a template within the shared folder, but the template is not visible by "User1" and it has to be explicitly shared with "User1"

I was expecting that any template created in the shared folder would be automatically shared between the two users. Is the behaviour above expected?

**Comment by martinjoconnor** [comment]
It should be visible. We will take a look.

**Comment by egyedia** [comment]
I tried to reproduce this on staging.
It worked for me. However, there could be a slight misunderstanding, which caused this issue being reported:
When you say "It is not visible by 'User1' ", you mean it is not explicitly visible in the "Shared with me" view, or you mean that there is no way that the user can reach it.

The "Shared with me" view shows only the folders and resources that are explicitly shared with the user. However, going into a shared folder will reveal its contents, and this is how I was able to see the resource on staging. Could you please check if you can see the given resource this way - going into the shared folder on the "Shared with me" view?

**Comment by agbeltran** [comment]
I meant it was not visible in the same folder that "User1" shared, not in "Shared with me". So, "User1" owns the folder, shares it with "User2", "User2" creates a template in that same folder and "User1" cannot see it. So, "User2" had to explicitly share the template that was in the folder owned by "User2". We tried this in production, not in staging.

**Comment by egyedia** [comment]
Thank you for clarifying this.
Yes, we were able to reproduce the scenario, and we agreed that this needs to be changed.
I will start working on this issue, we will include the change in the next release.
