### ISSUE TITLE
Read-only exploration of field controlled values

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#774]
Currently, users cannot browse the controlled terms for a field in a read-only way. The current dialog assume editing/creation.

We need to enhance the current dialog to allow this.

Particularly important for CDE work, where users want to explore value sets.

**Comment by willrett** [comment]
Read-only option added to the controlled terms dialog.

**Comment by marcosmro** [comment]
This issue required an additional fix: the the CADSR-VS ontology needed to be set as a value set collection in BioPortal. Documented at https://github.com/metadatacenter/cedar-template-editor/issues/825
