### ISSUE TITLE
Long description text overlaps the field selection menu

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-template-editor#785]
See the screenshot image below:

<img width="1053" alt="screen shot 2018-08-28 at 2 36 09 pm" src="https://user-images.githubusercontent.com/5062950/44752441-d13a2100-aacf-11e8-96e6-a1ee54ff9270.png">

**Comment by willrett** [comment]
Weird, I don't see that happening.  What browser are you using?

**Comment by willrett** [comment]
Fixed by changing the way the popup comes up.
