### ISSUE TITLE
The scrollbar in the search dialog scrolls the wrong side of the panel

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-template-editor#787]
See the screenshot image below:

<img width="846" alt="screen shot 2018-08-28 at 2 55 51 pm" src="https://user-images.githubusercontent.com/5062950/44753460-0136f380-aad3-11e8-8473-f0fbe535f997.png">

**Comment by johardi** [comment]
I think both panels should have their own scrollbar when the content is longer than the given dimension.

**Comment by willrett** [comment]
Swapped panels and changed the info panel display.
