### ISSUE TITLE
A published field shouldn't have the field selector menu bar

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-template-editor#789]
The image below shows a published CDE:

![screen shot 2018-08-29 at 3 17 25 pm](https://user-images.githubusercontent.com/5062950/44818693-c7cbba00-ab9e-11e8-814c-27eb753916df.png)

Hiding the field selector menu will prevent users to edit the published field. If users want to edit (or modify/update) the field, they need to start a new draft from it. I think this issue is also relevant to other types of CEDAR resource (i.e., elements and templates)

**Comment by willrett** [comment]
It is the same problem for locked templates and elements as well.  The approach we have taken with all of them is to show the locked icon in the upper right and give a warning once an edit has been made.
