### ISSUE TITLE
Need a better labelling other than 'Create Draft'

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-template-editor#790]
IMO, the menu label 'Create Draft' is too technical and a bit confusing. Perhaps 'Make a new version' would be better?

**Comment by martinjoconnor** [comment]
Or 'Make a new draft version'?

**Comment by graybeal** [comment]
What the person really wants to do is edit the thing, so I think it should say "Edit". I don't think we need a menu item that says "Create" anything. When they want to edit, they should just click on Edit. It can say "Edit (creates draft)" if we want to distinguish the fact this is a published document and we are creating a new one.

**Comment by martinjoconnor** [comment]
They are not editing it though. They are creating a new artifact - that they then edit. Being able to edit a non writable/modifiable thing would be odd.

**Comment by graybeal** [comment]
Either way of thinking about it is consistent ("Edit" includes creating a new editable one, or it doesn't.) My way just has one less scroll and one less click.

**Comment by willrett** [comment]
We don't have to use the word draft.  We could say "Create version" and "Publish version".
