### ISSUE TITLE
Use the label 'View' instead of 'Edit' for published resources for clarity

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-template-editor#791]
A published resource will have a read-only mode and because of that, the menu label in the workspace shouldn't say 'Edit' but 'View' instead.

<img width="1036" alt="screen shot 2018-08-30 at 2 21 23 pm" src="https://user-images.githubusercontent.com/5062950/44880066-3886db00-ac60-11e8-97de-64f675e23260.png">

**Comment by willrett** [comment]
Changed to use Open instead of Edit.
