### ISSUE TITLE
Show element and field version in Template Creator

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#803]
When a versioned field is added to a template there is no visual display of the version.

<img width="942" alt="screen shot 2018-09-04 at 3 55 36 pm" src="https://user-images.githubusercontent.com/1731323/45061947-8bdf9b80-b05b-11e8-9fc2-6d059c3b1666.png">

For CDE-based fields in particular this is useful information.

Same issue for versioned elements added to a template.

**Comment by willrett** [comment]
Added version to field/element header.
