### ISSUE TITLE
Show template, element and field versions in search results

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#804]
When searching for artifacts the version is not visually indicated.

e.g.,

<img width="804" alt="screen shot 2018-09-04 at 4 03 23 pm" src="https://user-images.githubusercontent.com/1731323/45062110-58e9d780-b05c-11e8-8c6f-a3c08594cab9.png">

<img width="802" alt="screen shot 2018-09-04 at 4 03 48 pm" src="https://user-images.githubusercontent.com/1731323/45062120-5b4c3180-b05c-11e8-8f11-3c1daae11ea6.png">

Important for CDEs, for example,

**Comment by willrett** [comment]
Added version to list and grid views.
