### ISSUE TITLE
Constrain the values of AIRR template Field Type

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-template-editor#805]
In the MiAIRR template, the values accepted by the NCBI for the File Type field in the SRA section are:

{'autodetect-xml', 'generic-data', 'phenotype-table', 'sra-study-xml-v1', 'sra-experiment-xml-v1', 'sra-sample-xml-v1', 'sra-run-xml-v1', 'sra-analysis-xml-v1', 'sra-study-xml-v2', 'sra-experiment-xml-v2', 'sra-sample-xml-v2', 'sra-run-xml-v2', 'sra-analysis-xml-v2', 'sra-run-454_native', 'sra-run-bam', 'sra-run-CompleteGenomics_native', 'sra-run-fastq', 'sra-run-Helicos_native', 'sra-run-PacBio_HDF5', 'sra-run-sff', 'sra-run-SOLiD_native', 'sra-run-srf', 'sra-run-OxfordNanopore_native', 'sra-run-reference_fasta', 'project-core-xml-v1', 'wgs-contigs-sqn', 'wgs-unplaced-scaffolds-agp', 'wgs-contig-replicon-descr', 'wgs-agp-replicon-descr', 'wgs-loc-chr-to-replicon', 'wgs-replicon-from-contigs-agp', 'wgs-scaffold-from-contigs-agp', 'wgs-replicon-from-scaffolds-agp', 'wgs-unlocalized-scaffolds-agp', 'wgs-unloc-scaffold-to-replicon', 'wgs-assembly-sqn', 'wgs-assembly-fasta', 'wgs-contigs-fasta', 'wgs-agp', 'wgs-placement', 'ena-wgs-flatfile', 'ddbj-wgs-flatfile', 'wgs-flatfile-preprocess-report', 'tsa-seqsubmit-sqn', 'complete-genomes-annotated-sqn', 'complete-genomes-annotate-sqn', 'complete-genomes-annotate-fasta', 'complete-genomes-annotate-template', 'complete-genomes-replicon', 'genbank-sqn', 'genbank-submission-package', 'genbank-barcode-tar', 'genbank-sequences-fasta', 'genbank-srcmods-tbl', 'genbank-ncbi-link-tbl', 'genbank-sequences-filtered-fasta', 'genbank-sequences-fastaval-xml', 'genbank-srcmods-filtered-tbl', 'genbank-sequences-report-txt', 'genbank-sequences-report-tbl', 'genbank-tools-versions-xml', 'genbank-features-table', 'genbank-features-filtered-table', 'methylation-data', 'sequences-fasta', 'bionano-cmap', 'bionano-coord', 'bionano-xmap', 'bionano-smap', 'bionano-bnx', 'sequin', 'antibiogram', 'modifications.csv', 'modifications.gff', 'motifs.gff', 'motif_summary.csv', 'biosample-tbl-v2.0', 'antibiogram-tbl-v1.0'}

We need to ask the AIRR community which of these values can be used in the MiAIRR template.

**Comment by graybeal** [comment]
Confirmed at Friday's MiniStds Working Group call that we can change this to a short list:
* sra_run_fastq
* sra-run-PacBio_HDF5

Based on comments at the meeting and in Yuriy's reply above, help text should say 
`The preferred submission format is sra_run_fastq, as Quality metadata is important to interpret the data. If you have fasta files and can provide quality information in the appropriate fields, use the sra_run_fastq selection and add an attribute-value pair with attribute='loader' and value='fastq-load.py'. Note that some PacBio instruments default to BAM files; these are not support for AIRR Community data at this time.`

**Comment by graybeal** [comment]
Whatever path we pick, it would be nice to support multiple file types (comma-separated), but I think is not required.

**Comment by graybeal** [comment]
The text still hasn't been updated. I'll open another ticket.
