### ISSUE TITLE
provide a uri for a term in a list

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-template-editor#81]
For list elements, there is an absence of a means to provide a source for the terms in the list, a URI for the source of the element's description or the source's term or identifier.

**Comment by martinjoconnor** [comment]
I changed his to a bug. This used to work.

**Comment by martinjoconnor** [comment]
All items on a check list and on a pull down should be linkable with ontology terms.

**Comment by willrett** [comment]
duplicate
