### ISSUE TITLE
Uneven item sizes in grid view 

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#814]
All rectangles should be the same size in grid view IMHO.

<img width="692" alt="screen shot 2018-09-07 at 1 44 57 pm" src="https://user-images.githubusercontent.com/1731323/45242390-a9ec0c80-b2a4-11e8-9d3f-91e734e40741.png">

Google Drive has them all the same size has a floating popup to show full title for truncated titles, e.g.,

<img width="422" alt="screen shot 2018-09-07 at 1 46 01 pm" src="https://user-images.githubusercontent.com/1731323/45242394-ae182a00-b2a4-11e8-9fa6-9ca7d95ec108.png">

**Comment by willrett** [comment]
I wish I could generate thumbnail images to show.  I make the titles one line with a tooltip for a title that overflows, and the boxes are now a fixed height.
