### ISSUE TITLE
Date field is not cross browser compatible

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-template-editor#817]
The date field works fine in Chrome, but it behaves strangely in Firefox and Safari.
- In Firefox, the date shown when the field is collapsed differs from the date shown when the field is expanded.
- In Safari, the field shows "Invalid Date".

See the following screenshots:

Chrome:
![chrome](https://user-images.githubusercontent.com/7634440/45380549-d01cef80-b5b7-11e8-8f42-7a7750ff4c91.png)

Firefox:
![screen shot 2018-09-11 at 11 41 25 am](https://user-images.githubusercontent.com/7634440/45380583-e88d0a00-b5b7-11e8-94d9-e3d251d03429.png)
![screen shot 2018-09-11 at 11 41 51 am](https://user-images.githubusercontent.com/7634440/45380558-dc08b180-b5b7-11e8-8f4c-2d9e28441a4a.png)

Safari:
![screen shot 2018-09-11 at 11 39 59 am](https://user-images.githubusercontent.com/7634440/45380613-f3e03580-b5b7-11e8-839f-b7a68f829568.png)

**Comment by willrett** [comment]
Fixed
