### ISSUE TITLE
Template designer doesn't validate the template

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-template-editor#826]
Step to reproduce:
1. Open a template (_Note: per 9/24 most of the templates are invalid due to the introduction of `skos`, `skos:prefLabel` and `skos:altLabel` fields_)
2. The editor says "Document is valid" although it is not.
<img width="734" alt="screen shot 2018-09-24 at 10 43 46 am" src="https://user-images.githubusercontent.com/5062950/45968824-d616c580-bfe6-11e8-90d9-19ed0aa6da22.png">

**Comment by willrett** [comment]
fixed
