### ISSUE TITLE
Element designer only does the validation when opening an element but not after saving it

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-template-editor#827]
Steps to reproduce:
1. Open an element (_Note: per 9/24 most of the elements are invalid due to the introduction of `skos`, `skos:prefLabel` and `skos:altLabel` fields_)
2. The element designer says "Document is invalid" which is true
<img width="571" alt="screen shot 2018-09-24 at 10 48 26 am" src="https://user-images.githubusercontent.com/5062950/45969031-67863780-bfe7-11e8-92db-fd4cd6c55f15.png">
3. Save the element and the element designer will say "Document is valid" although no fixes were made (i.e., no skos fields could be found)
<img width="480" alt="screen shot 2018-09-24 at 10 49 13 am" src="https://user-images.githubusercontent.com/5062950/45969097-96041280-bfe7-11e8-8ca8-a032f4465b9f.png">

**Comment by willrett** [comment]
fixed
