### ISSUE TITLE
Unwanted old title name when creating a new template/element/field 

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-template-editor#832]
Steps to reproduce:
1. Create a new template, put a name, add some fields and then save it
2. Exit to the workspace
3. Create another new template

The new template editor will have the same title as the previous template (see screenshot below):

<img width="429" alt="screen shot 2018-09-26 at 11 05 27 am" src="https://user-images.githubusercontent.com/5062950/46106852-b28e7f00-c18e-11e8-9f8c-b47d4ba90625.png">

**Comment by willrett** [comment]
I cannot reproduce this issue and will assume that it has been fixed.
