### ISSUE TITLE
Property search doesn't happen immediately when annotating an element

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-template-editor#835]
Steps to reproduce:
1. Create a template with an element inside,
2. Select the element and annotate it with a standard term (i.e., clicking the "RDF-Triangle" icon)
3. Nothing happened

Workaround: Click on the gear icon and select the option "Search for a property in BioPortal" manually and it will start the searching and show the search result

However, the interface has a missing OK button to confirm my selection.

**Comment by willrett** [comment]
fixed
