### ISSUE TITLE
Unable to reposition template elements in a template

### ISSUE THREAD

**Issue by johardi** [metadatacenter/cedar-template-editor#836]
Steps to reproduce:
1. Create a template with several template fields and elements
2. Reposition a template element by clicking-and-dragging
3. Nothing happened

**Comment by johardi** [comment]
UPDATE:
This behavior only happened when the template element is at the very top and I would like to move it to a lower position. Moving the template field didn't do any good either.

**Comment by willrett** [comment]
Can't duplicate this behavior.  Can you give me a list of actions which will show the problem.

**Comment by johardi** [comment]
I found this issue is no longer a problem in the most recent update in the staging server, so case closed!
