### ISSUE TITLE
Deleting a workspace item results in a different item disappearing from view

### ISSUE THREAD

**Issue by rsgoncalves** [metadatacenter/cedar-template-editor#838]
After deleting an item in the workspace (folder, instance, template,..), some other item disappears from the workspace while the deleted one stays visible. The exception to this is deleting the very first item in the workspace.

Only after refreshing, or doing an operation that requires a refresh of the workspace (such as adding a new item), does the deleted item actually disappear from the workspace.

**Comment by willrett** [comment]
fixed
