### ISSUE TITLE
Templates need version field

### ISSUE THREAD

**Issue by willrett** [metadatacenter/cedar-template-editor#84]
The templates lack a means of indicating provenance except as free text in the description. This should include a version indicator.  ImmPort templates are versioned for each software release.

**Comment by martinjoconnor** [comment]
Related to metadatacenter/cedar-template-server#6 on the server side.

**Comment by martinjoconnor** [comment]
Duplicate of https://github.com/metadatacenter/cedar-model-validation-library/issues/16
