### ISSUE TITLE
More informative search string in Template Creator

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#841]
Current search text says "Search the workspace" but does not say for what. Perhaps change to "Search for elements and fields".

<img width="1065" alt="screen shot 2018-10-26 at 10 05 31 am" src="https://user-images.githubusercontent.com/1731323/47583619-d91a1400-d90c-11e8-9790-a9326e72179d.png">

**Comment by willrett** [comment]
fixed
