### ISSUE TITLE
Exception messages not being displayed in error dialog

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#889]
In some cases (e.g., invalid templates) errors are not being displayed by the error dialog box.

![Screen Shot 2020-08-05 at 5.17.19 PM.png](https://images.zenhubusercontent.com/559ac6c34f7a08fbb7f3984b/c03d7b1c-a12c-48c5-bd38-efa7f723c036)

**Comment by egyedia** [comment]
Added validation info to the body of BadRequest, also made UI side to show more info
