### ISSUE TITLE
Add property icon should not be present for fields in Template Designer

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-template-editor#891]
Properties cannot be assigned at the field level (they can only be assigned between templates/elements and fields inside them) so the Add Property icon should be removed. (It has no effect at present)

![Screen Shot 2022-08-09 at 10.37.38 AM.png](https://images.zenhubusercontent.com/559ac6c34f7a08fbb7f3984b/f36ed01e-2f64-48cb-93d7-e52d7c0f443f)

**Comment by muakdogan** [comment]
Fixed with PR #939
