### ISSUE TITLE
Metadata editor presentation of multiple values needs redesigning and implementing

### ISSUE THREAD

**Issue by matthewhorridge** [metadatacenter/cedar-template-editor#895]
The presentation of multiple values in the metadata is unintuitive, seems to go against established UI conventions and is plain confusing.  I've heard multiple complaints from multiple sources about this.  I am not aware of the history of this component, so with that in mind, these are my observations.

Here are the problems:

1) The "Copy" button, with the copy icon, goes against established conventions. In general, "copy" means, "copy the selected item to the clipboard", but this isn't what the copy button does.

2) It's not obvious how to add a new value.  This is because "Add" is actually "Copy".

3) When adding new values, the current value field values are duplicated in the fresh/new value.  This is disconcerting because it looks like nothing has happened (there is only a very slight change in the UI) and I find that I have to manually clear out these duplicated values to enter the ones that I really want. 

4) Only one value is visible at a time.  This is inefficient.  I, personally, would prefer a vertical arrangement, with all values visible.  The Open View presentation is more acceptable IMO.

**Comment by muakdogan** [comment]
This issue is addressed in the new "CEE".
