### ISSUE TITLE
Add mechanism to quickly copy Folder Ids

### ISSUE THREAD

**Issue by matthewhorridge** [metadatacenter/cedar-template-editor#896]
When working with CEDAR and external tools that inteact with CEDAR via its API I find my self frequently copying the folder id (both the URI and the short UUID) from the part of the URL that contains it.  This is fiddly and time consuming.  I would love a mechanism (button) to copy folder Ids from various places in the UI.  These places could be:

1) The dropdown menu from the folder id

<img width="635" alt="image" src="https://user-images.githubusercontent.com/488607/203144245-65d612d3-d5f5-4bf8-a214-75c8bb49fa52.png">

2) The "info panel" for the selected folder id

<img width="956" alt="image" src="https://user-images.githubusercontent.com/488607/203144351-7fbd014e-d4af-45d6-985d-fc1edf43f8cf.png">

3) The containing folder id for a given template or instance, both in the drop down menu and the info panel and in the editing page for the artifact.

**Comment by graybeal** [comment]
Please drop the last phrase of #3 "and in the editing page for the artifact" and create a new ticket that includes adding drop-down metadata to both the template designer and the metadata editor, and adding these URLs to both of those and also the OpenView. (Or make that 3 tickets, one for each app.)

**Comment by muakdogan** [comment]
For @graybeal 's request issue #947 is open. Others are done and closed with PR @ #946
