### ISSUE TITLE
Type Filter for artifacts in the dashboard is confusing and ambiguous

### ISSUE THREAD

**Issue by matthewhorridge** [metadatacenter/cedar-template-editor#898]
The "Type" filter, for templates, elements, fields and instances is hard to decipher.  It is ambiguous and doesn't clearly indicate that a filter is active or what is shown.

See this example, what is included and shown by the filter?

<img width="366" alt="image" src="https://user-images.githubusercontent.com/488607/203145576-c2603207-3128-4b57-92dd-92a293a54862.png">

Similarly,

<img width="362" alt="image" src="https://user-images.githubusercontent.com/488607/203145725-09500665-079b-4aba-b356-fb8853ef6548.png">

What is highlighted, what is not?

I suggest replacing this with a simple checkbox list so it's clear what is selected and what is not.

**Comment by muakdogan** [comment]
Improved and closed with PR #935
