### ISSUE TITLE
Improve Navigation in Metadata Editor:  Add Expand/Collapse All

### ISSUE THREAD

**Issue by matthewhorridge** [metadatacenter/cedar-template-editor#899]
The various elements/fields in the metadata editor are collapsable (see below).  Sometimes I want to be able to collapse everything and then scroll through to what I actually want to see and expand just that one thing.  Add support for expand/collapse all.

<img width="809" alt="image" src="https://user-images.githubusercontent.com/488607/203149047-b62a72a0-4996-4d9b-b2de-d81ea1926522.png">

**Comment by muakdogan** [comment]
Implemented in Embeddable editor that will substitute current metadata editor in near future.
