### ISSUE TITLE
Some fields are not displayed

### ISSUE THREAD

**Issue by yancao77** [metadatacenter/cedar-template-editor#979]
While populating an instance of the Radx-rad Metadata Specification using the template editor, I noticed the absence of the Subject Identifier Scheme field. However, upon switching to the CEE, the field becomes visible. It's worth mentioning that this field has a default value, which may be related to the issue.
<img width="882" alt="Screenshot 2024-03-18 at 2 53 14 PM" src="https://github.com/metadatacenter/cedar-template-editor/assets/131015250/f1706398-7dae-4293-b6d8-cc2d02654249">

<img width="675" alt="Screenshot 2024-03-18 at 2 52 43 PM" src="https://github.com/metadatacenter/cedar-template-editor/assets/131015250/aca5898a-884d-4774-a897-c296fe372c4a">

<img width="813" alt="Screenshot 2024-03-18 at 2 54 44 PM" src="https://github.com/metadatacenter/cedar-template-editor/assets/131015250/3a6026b2-fafe-4f12-bc96-67d3304a8c3e">

**Comment by egyedia** [comment]
The given field is a hidden field.
Actually the CEE is the one not behaving properly here.

**Comment by muakdogan** [comment]
This is because field is hidden. I implemented hiding of "hidden" fields in CEE but it may have not hit the production yet.

**Comment by muakdogan** [comment]
This is because field is hidden. I implemented hiding of "hidden" fields in CEE but it may have not hit the production yet.
